"""Generate NIST-family catalog JSONs (all public domain — Tier A).

Produces:
- nist-800-171-r2      — DoD CUI requirements (Rev 2, 2020)
- nist-800-171-r3      — DoD CUI requirements (Rev 3, 2024)
- nist-800-172         — Enhanced protections against APTs (2021)
- nist-ai-rmf-1.0      — AI Risk Management Framework (2023)
- nist-privacy-framework-1.0 — Privacy Framework v1.0 (2020)
- nist-ssdf-800-218    — Secure Software Development Framework (2022)
"""

from __future__ import annotations

from _generators import emit_control_catalog  # type: ignore[import-not-found]

NIST_PD_SOURCE = "NIST (U.S. Government work, public domain)"


# ---------------------------------------------------------------------------
# NIST SP 800-171 Rev 2 — Protecting CUI in Nonfederal Systems
# ---------------------------------------------------------------------------

NIST_800_171_R2 = [
    # Family 3.1 — Access Control
    ("3.1.1", "Limit system access to authorized users", "3.1 Access Control"),
    ("3.1.2", "Limit system access to the types of transactions and functions that authorized users are permitted to execute", "3.1 Access Control"),
    ("3.1.3", "Control the flow of CUI in accordance with approved authorizations", "3.1 Access Control"),
    ("3.1.4", "Separate the duties of individuals to reduce the risk of malevolent activity without collusion", "3.1 Access Control"),
    ("3.1.5", "Employ the principle of least privilege", "3.1 Access Control"),
    ("3.1.6", "Use non-privileged accounts or roles when accessing nonsecurity functions", "3.1 Access Control"),
    ("3.1.7", "Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs", "3.1 Access Control"),
    ("3.1.8", "Limit unsuccessful logon attempts", "3.1 Access Control"),
    ("3.1.9", "Provide privacy and security notices consistent with applicable CUI rules", "3.1 Access Control"),
    ("3.1.10", "Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity", "3.1 Access Control"),
    ("3.1.11", "Terminate user sessions after a defined condition", "3.1 Access Control"),
    ("3.1.12", "Monitor and control remote access sessions", "3.1 Access Control"),
    ("3.1.13", "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions", "3.1 Access Control"),
    ("3.1.14", "Route remote access via managed access control points", "3.1 Access Control"),
    ("3.1.15", "Authorize remote execution of privileged commands and remote access to security-relevant information", "3.1 Access Control"),
    ("3.1.16", "Authorize wireless access prior to allowing such connections", "3.1 Access Control"),
    ("3.1.17", "Protect wireless access using authentication and encryption", "3.1 Access Control"),
    ("3.1.18", "Control connection of mobile devices", "3.1 Access Control"),
    ("3.1.19", "Encrypt CUI on mobile devices and mobile computing platforms", "3.1 Access Control"),
    ("3.1.20", "Verify and control/limit connections to and use of external systems", "3.1 Access Control"),
    ("3.1.21", "Limit use of organizational portable storage devices on external systems", "3.1 Access Control"),
    ("3.1.22", "Control CUI posted or processed on publicly accessible systems", "3.1 Access Control"),
    # Family 3.2 — Awareness and Training
    ("3.2.1", "Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of applicable policies, standards, and procedures", "3.2 Awareness and Training"),
    ("3.2.2", "Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities", "3.2 Awareness and Training"),
    ("3.2.3", "Provide security awareness training on recognizing and reporting potential indicators of insider threat", "3.2 Awareness and Training"),
    # Family 3.3 — Audit and Accountability
    ("3.3.1", "Create and retain system audit logs and records to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity", "3.3 Audit and Accountability"),
    ("3.3.2", "Ensure that the actions of individual system users can be uniquely traced so they can be held accountable for their actions", "3.3 Audit and Accountability"),
    ("3.3.3", "Review and update logged events", "3.3 Audit and Accountability"),
    ("3.3.4", "Alert in the event of an audit logging process failure", "3.3 Audit and Accountability"),
    ("3.3.5", "Correlate audit record review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity", "3.3 Audit and Accountability"),
    ("3.3.6", "Provide audit record reduction and report generation to support on-demand analysis and reporting", "3.3 Audit and Accountability"),
    ("3.3.7", "Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records", "3.3 Audit and Accountability"),
    ("3.3.8", "Protect audit information and audit logging tools from unauthorized access, modification, and deletion", "3.3 Audit and Accountability"),
    ("3.3.9", "Limit management of audit logging functionality to a subset of privileged users", "3.3 Audit and Accountability"),
    # Family 3.4 — Configuration Management
    ("3.4.1", "Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles", "3.4 Configuration Management"),
    ("3.4.2", "Establish and enforce security configuration settings for IT products employed in organizational systems", "3.4 Configuration Management"),
    ("3.4.3", "Track, review, approve or disapprove, and log changes to organizational systems", "3.4 Configuration Management"),
    ("3.4.4", "Analyze the security impact of changes prior to implementation", "3.4 Configuration Management"),
    ("3.4.5", "Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems", "3.4 Configuration Management"),
    ("3.4.6", "Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities", "3.4 Configuration Management"),
    ("3.4.7", "Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services", "3.4 Configuration Management"),
    ("3.4.8", "Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software", "3.4 Configuration Management"),
    ("3.4.9", "Control and monitor user-installed software", "3.4 Configuration Management"),
    # Family 3.5 — Identification and Authentication
    ("3.5.1", "Identify system users, processes acting on behalf of users, and devices", "3.5 Identification and Authentication"),
    ("3.5.2", "Authenticate (or verify) the identities of users, processes, or devices as a prerequisite to allowing access to organizational systems", "3.5 Identification and Authentication"),
    ("3.5.3", "Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts", "3.5 Identification and Authentication"),
    ("3.5.4", "Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts", "3.5 Identification and Authentication"),
    ("3.5.5", "Prevent reuse of identifiers for a defined period", "3.5 Identification and Authentication"),
    ("3.5.6", "Disable identifiers after a defined period of inactivity", "3.5 Identification and Authentication"),
    ("3.5.7", "Enforce a minimum password complexity and change of characters when new passwords are created", "3.5 Identification and Authentication"),
    ("3.5.8", "Prohibit password reuse for a specified number of generations", "3.5 Identification and Authentication"),
    ("3.5.9", "Allow temporary password use for system logons with an immediate change to a permanent password", "3.5 Identification and Authentication"),
    ("3.5.10", "Store and transmit only cryptographically-protected passwords", "3.5 Identification and Authentication"),
    ("3.5.11", "Obscure feedback of authentication information", "3.5 Identification and Authentication"),
    # Family 3.6 — Incident Response
    ("3.6.1", "Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities", "3.6 Incident Response"),
    ("3.6.2", "Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization", "3.6 Incident Response"),
    ("3.6.3", "Test the organizational incident response capability", "3.6 Incident Response"),
    # Family 3.7 — Maintenance
    ("3.7.1", "Perform maintenance on organizational systems", "3.7 Maintenance"),
    ("3.7.2", "Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance", "3.7 Maintenance"),
    ("3.7.3", "Ensure equipment removed for off-site maintenance is sanitized of any CUI", "3.7 Maintenance"),
    ("3.7.4", "Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems", "3.7 Maintenance"),
    ("3.7.5", "Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete", "3.7 Maintenance"),
    ("3.7.6", "Supervise the maintenance activities of maintenance personnel without required access authorization", "3.7 Maintenance"),
    # Family 3.8 — Media Protection
    ("3.8.1", "Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital", "3.8 Media Protection"),
    ("3.8.2", "Limit access to CUI on system media to authorized users", "3.8 Media Protection"),
    ("3.8.3", "Sanitize or destroy system media containing CUI before disposal or release for reuse", "3.8 Media Protection"),
    ("3.8.4", "Mark media with necessary CUI markings and distribution limitations", "3.8 Media Protection"),
    ("3.8.5", "Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas", "3.8 Media Protection"),
    ("3.8.6", "Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards", "3.8 Media Protection"),
    ("3.8.7", "Control the use of removable media on system components", "3.8 Media Protection"),
    ("3.8.8", "Prohibit the use of portable storage devices when such devices have no identifiable owner", "3.8 Media Protection"),
    ("3.8.9", "Protect the confidentiality of backup CUI at storage locations", "3.8 Media Protection"),
    # Family 3.9 — Personnel Security
    ("3.9.1", "Screen individuals prior to authorizing access to organizational systems containing CUI", "3.9 Personnel Security"),
    ("3.9.2", "Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers", "3.9 Personnel Security"),
    # Family 3.10 — Physical Protection
    ("3.10.1", "Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals", "3.10 Physical Protection"),
    ("3.10.2", "Protect and monitor the physical facility and support infrastructure for organizational systems", "3.10 Physical Protection"),
    ("3.10.3", "Escort visitors and monitor visitor activity", "3.10 Physical Protection"),
    ("3.10.4", "Maintain audit logs of physical access", "3.10 Physical Protection"),
    ("3.10.5", "Control and manage physical access devices", "3.10 Physical Protection"),
    ("3.10.6", "Enforce safeguarding measures for CUI at alternate work sites", "3.10 Physical Protection"),
    # Family 3.11 — Risk Assessment
    ("3.11.1", "Periodically assess the risk to organizational operations, organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI", "3.11 Risk Assessment"),
    ("3.11.2", "Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified", "3.11 Risk Assessment"),
    ("3.11.3", "Remediate vulnerabilities in accordance with risk assessments", "3.11 Risk Assessment"),
    # Family 3.12 — Security Assessment
    ("3.12.1", "Periodically assess the security controls in organizational systems to determine if the controls are effective in their application", "3.12 Security Assessment"),
    ("3.12.2", "Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems", "3.12 Security Assessment"),
    ("3.12.3", "Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls", "3.12 Security Assessment"),
    ("3.12.4", "Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems", "3.12 Security Assessment"),
    # Family 3.13 — System and Communications Protection
    ("3.13.1", "Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems", "3.13 System and Communications Protection"),
    ("3.13.2", "Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems", "3.13 System and Communications Protection"),
    ("3.13.3", "Separate user functionality from system management functionality", "3.13 System and Communications Protection"),
    ("3.13.4", "Prevent unauthorized and unintended information transfer via shared system resources", "3.13 System and Communications Protection"),
    ("3.13.5", "Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks", "3.13 System and Communications Protection"),
    ("3.13.6", "Deny network communications traffic by default and allow network communications traffic by exception", "3.13 System and Communications Protection"),
    ("3.13.7", "Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (i.e., split tunneling)", "3.13 System and Communications Protection"),
    ("3.13.8", "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards", "3.13 System and Communications Protection"),
    ("3.13.9", "Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity", "3.13 System and Communications Protection"),
    ("3.13.10", "Establish and manage cryptographic keys for cryptography employed in organizational systems", "3.13 System and Communications Protection"),
    ("3.13.11", "Employ FIPS-validated cryptography when used to protect the confidentiality of CUI", "3.13 System and Communications Protection"),
    ("3.13.12", "Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device", "3.13 System and Communications Protection"),
    ("3.13.13", "Control and monitor the use of mobile code", "3.13 System and Communications Protection"),
    ("3.13.14", "Control and monitor the use of Voice over Internet Protocol (VoIP) technologies", "3.13 System and Communications Protection"),
    ("3.13.15", "Protect the authenticity of communications sessions", "3.13 System and Communications Protection"),
    ("3.13.16", "Protect the confidentiality of CUI at rest", "3.13 System and Communications Protection"),
    # Family 3.14 — System and Information Integrity
    ("3.14.1", "Identify, report, and correct system flaws in a timely manner", "3.14 System and Information Integrity"),
    ("3.14.2", "Provide protection from malicious code at designated locations within organizational systems", "3.14 System and Information Integrity"),
    ("3.14.3", "Monitor system security alerts and advisories and take action in response", "3.14 System and Information Integrity"),
    ("3.14.4", "Update malicious code protection mechanisms when new releases are available", "3.14 System and Information Integrity"),
    ("3.14.5", "Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed", "3.14 System and Information Integrity"),
    ("3.14.6", "Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks", "3.14 System and Information Integrity"),
    ("3.14.7", "Identify unauthorized use of organizational systems", "3.14 System and Information Integrity"),
]


def _controls_from_tuples(tuples: list[tuple[str, str, str]]) -> list[dict]:
    return [{"id": cid, "title": title, "description": title, "family": family} for cid, title, family in tuples]


emit_control_catalog(
    framework_id="nist-800-171-r2",
    framework_name="NIST SP 800-171 Rev 2 — Protecting CUI in Nonfederal Systems",
    version="Rev 2 (2020)",
    source=NIST_PD_SOURCE + " — https://csrc.nist.gov/publications/detail/sp/800-171/rev-2/final",
    families=sorted({fam for _, _, fam in NIST_800_171_R2}),
    controls=_controls_from_tuples(NIST_800_171_R2),
    tier="A",
)


# ---------------------------------------------------------------------------
# NIST SP 800-171 Rev 3 — Revised CUI requirements (May 2024)
# ---------------------------------------------------------------------------

NIST_800_171_R3 = [
    # Rev 3 restructured into 17 families; IDs follow NIST Rev 3 catalog
    # We mirror Rev 2 + adds for Planning, System & Services Acquisition, Supply Chain
    ("03.01.01", "Account Management", "3.1 Access Control"),
    ("03.01.02", "Access Enforcement", "3.1 Access Control"),
    ("03.01.03", "Information Flow Enforcement", "3.1 Access Control"),
    ("03.01.04", "Separation of Duties", "3.1 Access Control"),
    ("03.01.05", "Least Privilege", "3.1 Access Control"),
    ("03.01.06", "Least Privilege — Privileged Accounts", "3.1 Access Control"),
    ("03.01.07", "Least Privilege — Privileged Functions", "3.1 Access Control"),
    ("03.01.08", "Unsuccessful Logon Attempts", "3.1 Access Control"),
    ("03.01.09", "System Use Notification", "3.1 Access Control"),
    ("03.01.10", "Device Lock", "3.1 Access Control"),
    ("03.01.11", "Session Termination", "3.1 Access Control"),
    ("03.01.12", "Remote Access", "3.1 Access Control"),
    ("03.01.16", "Wireless Access", "3.1 Access Control"),
    ("03.01.18", "Access Control for Mobile Devices", "3.1 Access Control"),
    ("03.01.20", "Use of External Systems", "3.1 Access Control"),
    ("03.01.22", "Publicly Accessible Content", "3.1 Access Control"),
    ("03.02.01", "Literacy Training and Awareness", "3.2 Awareness and Training"),
    ("03.02.02", "Role-Based Training", "3.2 Awareness and Training"),
    ("03.03.01", "Event Logging", "3.3 Audit and Accountability"),
    ("03.03.02", "Audit Record Content", "3.3 Audit and Accountability"),
    ("03.03.03", "Audit Record Generation", "3.3 Audit and Accountability"),
    ("03.03.04", "Response to Audit Logging Process Failures", "3.3 Audit and Accountability"),
    ("03.03.05", "Audit Record Review, Analysis, and Reporting", "3.3 Audit and Accountability"),
    ("03.03.06", "Audit Record Reduction and Report Generation", "3.3 Audit and Accountability"),
    ("03.03.07", "Time Stamps", "3.3 Audit and Accountability"),
    ("03.03.08", "Protection of Audit Information", "3.3 Audit and Accountability"),
    ("03.04.01", "Baseline Configuration", "3.4 Configuration Management"),
    ("03.04.02", "Configuration Settings", "3.4 Configuration Management"),
    ("03.04.03", "Configuration Change Control", "3.4 Configuration Management"),
    ("03.04.04", "Impact Analyses", "3.4 Configuration Management"),
    ("03.04.05", "Access Restrictions for Change", "3.4 Configuration Management"),
    ("03.04.06", "Least Functionality", "3.4 Configuration Management"),
    ("03.04.08", "Authorized Software — Allow by Exception", "3.4 Configuration Management"),
    ("03.04.10", "System Component Inventory", "3.4 Configuration Management"),
    ("03.04.11", "Information Location", "3.4 Configuration Management"),
    ("03.04.12", "System and Component Configuration for High-Risk Areas", "3.4 Configuration Management"),
    ("03.05.01", "User Identification and Authentication", "3.5 Identification and Authentication"),
    ("03.05.02", "Device Identification and Authentication", "3.5 Identification and Authentication"),
    ("03.05.03", "Multi-Factor Authentication", "3.5 Identification and Authentication"),
    ("03.05.04", "Replay-Resistant Authentication", "3.5 Identification and Authentication"),
    ("03.05.05", "Identifier Management", "3.5 Identification and Authentication"),
    ("03.05.07", "Password Management", "3.5 Identification and Authentication"),
    ("03.05.11", "Authentication Feedback", "3.5 Identification and Authentication"),
    ("03.05.12", "Authenticator Management", "3.5 Identification and Authentication"),
    ("03.06.01", "Incident Handling", "3.6 Incident Response"),
    ("03.06.02", "Incident Monitoring, Reporting, and Response Assistance", "3.6 Incident Response"),
    ("03.06.03", "Incident Response Testing", "3.6 Incident Response"),
    ("03.06.04", "Incident Response Training", "3.6 Incident Response"),
    ("03.06.05", "Incident Response Plan", "3.6 Incident Response"),
    ("03.07.04", "Maintenance Tools", "3.7 Maintenance"),
    ("03.07.05", "Nonlocal Maintenance", "3.7 Maintenance"),
    ("03.07.06", "Maintenance Personnel", "3.7 Maintenance"),
    ("03.08.01", "Media Storage", "3.8 Media Protection"),
    ("03.08.02", "Media Access", "3.8 Media Protection"),
    ("03.08.03", "Media Sanitization", "3.8 Media Protection"),
    ("03.08.04", "Media Marking", "3.8 Media Protection"),
    ("03.08.05", "Media Transport", "3.8 Media Protection"),
    ("03.08.07", "Media Use", "3.8 Media Protection"),
    ("03.08.09", "System Backup — Cryptographic Protection", "3.8 Media Protection"),
    ("03.09.01", "Personnel Screening", "3.9 Personnel Security"),
    ("03.09.02", "Personnel Termination and Transfer", "3.9 Personnel Security"),
    ("03.10.01", "Physical Access Authorizations", "3.10 Physical Protection"),
    ("03.10.02", "Monitoring Physical Access", "3.10 Physical Protection"),
    ("03.10.06", "Alternate Work Site", "3.10 Physical Protection"),
    ("03.10.07", "Physical Access Control", "3.10 Physical Protection"),
    ("03.10.08", "Access Control for Transmission", "3.10 Physical Protection"),
    ("03.11.01", "Risk Assessment", "3.11 Risk Assessment"),
    ("03.11.02", "Vulnerability Monitoring and Scanning", "3.11 Risk Assessment"),
    ("03.11.04", "Risk Response", "3.11 Risk Assessment"),
    ("03.12.01", "Security Assessment", "3.12 Security Assessment and Monitoring"),
    ("03.12.02", "Plan of Action and Milestones", "3.12 Security Assessment and Monitoring"),
    ("03.12.03", "Continuous Monitoring", "3.12 Security Assessment and Monitoring"),
    ("03.12.05", "Information Exchange", "3.12 Security Assessment and Monitoring"),
    ("03.13.01", "Boundary Protection", "3.13 System and Communications Protection"),
    ("03.13.04", "Information in Shared System Resources", "3.13 System and Communications Protection"),
    ("03.13.06", "Network Communications — Deny by Default", "3.13 System and Communications Protection"),
    ("03.13.08", "Transmission and Storage Confidentiality", "3.13 System and Communications Protection"),
    ("03.13.09", "Network Disconnect", "3.13 System and Communications Protection"),
    ("03.13.10", "Cryptographic Key Establishment and Management", "3.13 System and Communications Protection"),
    ("03.13.11", "Cryptographic Protection", "3.13 System and Communications Protection"),
    ("03.13.12", "Collaborative Computing Devices and Applications", "3.13 System and Communications Protection"),
    ("03.13.13", "Mobile Code", "3.13 System and Communications Protection"),
    ("03.13.15", "Session Authenticity", "3.13 System and Communications Protection"),
    ("03.14.01", "Flaw Remediation", "3.14 System and Information Integrity"),
    ("03.14.02", "Malicious Code Protection", "3.14 System and Information Integrity"),
    ("03.14.03", "Security Alerts, Advisories, and Directives", "3.14 System and Information Integrity"),
    ("03.14.06", "System Monitoring", "3.14 System and Information Integrity"),
    ("03.14.08", "Information Management and Retention", "3.14 System and Information Integrity"),
    ("03.15.01", "Policy and Procedures", "3.15 Planning"),
    ("03.15.02", "System Security Plan", "3.15 Planning"),
    ("03.15.03", "Rules of Behavior", "3.15 Planning"),
    ("03.16.01", "Allocation of Resources", "3.16 System and Services Acquisition"),
    ("03.16.02", "System Development Life Cycle", "3.16 System and Services Acquisition"),
    ("03.16.03", "External System Services", "3.16 System and Services Acquisition"),
    ("03.17.01", "Supply Chain Risk Management Plan", "3.17 Supply Chain Risk Management"),
    ("03.17.02", "Acquisition Strategies, Tools, and Methods", "3.17 Supply Chain Risk Management"),
    ("03.17.03", "Supply Chain Controls and Processes", "3.17 Supply Chain Risk Management"),
]

emit_control_catalog(
    framework_id="nist-800-171-r3",
    framework_name="NIST SP 800-171 Rev 3 — Protecting CUI in Nonfederal Systems",
    version="Rev 3 (May 2024)",
    source=NIST_PD_SOURCE + " — https://csrc.nist.gov/pubs/sp/800/171/r3/final",
    families=sorted({fam for _, _, fam in NIST_800_171_R3}),
    controls=_controls_from_tuples(NIST_800_171_R3),
    tier="A",
)


# ---------------------------------------------------------------------------
# NIST SP 800-172 — Enhanced Security Requirements for CUI (APT protections)
# ---------------------------------------------------------------------------

NIST_800_172 = [
    ("3.1.1e", "Employ dual authorization to execute critical or sensitive system and organizational operations", "3.1 Access Control"),
    ("3.1.2e", "Restrict access to systems and system components to only those information resources that are owned, provisioned, or issued by the organization", "3.1 Access Control"),
    ("3.1.3e", "Employ secure information transfer solutions to control information flows between security domains on connected systems", "3.1 Access Control"),
    ("3.2.1e", "Provide awareness training focused on recognizing and responding to threats from social engineering, advanced persistent threat actors, breaches, and suspicious behaviors", "3.2 Awareness and Training"),
    ("3.2.2e", "Include practical exercises in awareness training that are aligned with current threat scenarios and provide feedback to individuals involved in the training and their supervisors", "3.2 Awareness and Training"),
    ("3.3.1e", "Deploy an audit record generation capability that provides an organization-defined level of auditing of user-level and system-level activities that supports real-time alerting and analysis", "3.3 Audit and Accountability"),
    ("3.4.1e", "Establish and maintain an authoritative source and repository to provide a trusted source and accountability for approved and implemented system components", "3.4 Configuration Management"),
    ("3.4.2e", "Employ automated mechanisms to detect misconfigured or unauthorized system components and place components that cannot be remediated into a quarantine or remediation network", "3.4 Configuration Management"),
    ("3.4.3e", "Employ automated discovery and management tools to maintain an up-to-date, complete, accurate, and readily available inventory of system components", "3.4 Configuration Management"),
    ("3.5.1e", "Identify and authenticate systems and system components, where possible, before establishing a network connection using bidirectional authentication that is cryptographically-based and replay-resistant", "3.5 Identification and Authentication"),
    ("3.5.2e", "Employ automated mechanisms for the generation, protection, rotation, and management of passwords for systems and system components that do not support multifactor authentication or complex account management", "3.5 Identification and Authentication"),
    ("3.5.3e", "Employ automated or manual/procedural mechanisms to prohibit system components from connecting to organizational systems unless the components are known, authenticated, in a properly configured state, or in a trust profile", "3.5 Identification and Authentication"),
    ("3.6.1e", "Establish and maintain a security operations center capability that facilitates a 24/7 response capability", "3.6 Incident Response"),
    ("3.6.2e", "Establish and maintain a cyber incident response team that can be deployed by the organization within 24 hours", "3.6 Incident Response"),
    ("3.11.1e", "Employ threat intelligence, at a minimum from open or commercial sources and any DoD-provided sources, as part of a risk assessment to guide and inform the development of organizational systems, security architectures, selection of security solutions, monitoring, threat hunting, and response and recovery activities", "3.11 Risk Assessment"),
    ("3.11.2e", "Conduct cyber threat hunting activities to search for indicators of compromise in organizational systems and detect, track, and disrupt threats that evade existing controls", "3.11 Risk Assessment"),
    ("3.11.3e", "Employ advanced automation and analytics capabilities in support of analysts to predict and identify risks to organizations, systems, and system components", "3.11 Risk Assessment"),
    ("3.11.4e", "Document or reference in the system security plan the security solution selected, the rationale for the security solution, and the risk determination", "3.11 Risk Assessment"),
    ("3.11.5e", "Assess the effectiveness of security solutions at least annually to address anticipated risk and to respond to a continually evolving threat landscape", "3.11 Risk Assessment"),
    ("3.11.6e", "Assess, respond to, and monitor supply chain risks associated with organizational systems and system components", "3.11 Risk Assessment"),
    ("3.11.7e", "Develop a plan for managing supply chain risks associated with organizational systems and system components; update the plan at least annually and upon receipt of relevant cyber threat information", "3.11 Risk Assessment"),
    ("3.12.1e", "Conduct penetration testing at least annually, leveraging automated scanning tools and ad hoc tests using subject matter experts", "3.12 Security Assessment"),
    ("3.13.1e", "Employ diverse system components to reduce the extent of malicious code propagation", "3.13 System and Communications Protection"),
    ("3.13.2e", "Employ a physically or logically isolated subnetwork with managed interfaces to restrict communications traffic from systems that process CUI to systems with other data protection requirements", "3.13 System and Communications Protection"),
    ("3.13.3e", "Enforce design, implementation, and operation principles to maximize the use of automation and to minimize the use of trust between system components", "3.13 System and Communications Protection"),
    ("3.13.4e", "Employ technical and procedural means to confuse and mislead adversaries through a combination of misdirection, tainting, or disinformation", "3.13 System and Communications Protection"),
    ("3.13.5e", "Employ technical means to dynamically change aspects of organizational systems, system components, locations of critical functions/resources, or system configurations to increase the attack surface uncertainty and the level of effort required of adversaries", "3.13 System and Communications Protection"),
    ("3.14.1e", "Verify the integrity of security-critical and essential software using root of trust mechanisms or cryptographic signatures", "3.14 System and Information Integrity"),
    ("3.14.2e", "Monitor organizational systems and system components on an ongoing basis for anomalous or suspicious behavior", "3.14 System and Information Integrity"),
    ("3.14.3e", "Employ technical and procedural means to analyze events, incidents, alerts, security advisories, and related information on a real-time or near-real-time basis", "3.14 System and Information Integrity"),
    ("3.14.4e", "Refresh organizational systems and system components from a known, trusted state periodically", "3.14 System and Information Integrity"),
    ("3.14.5e", "Conduct reviews of persistent organizational storage locations periodically and remove CUI that is no longer needed", "3.14 System and Information Integrity"),
    ("3.14.6e", "Use threat indicator information and effective mitigations obtained from organizational or external sources to guide and inform intrusion detection and threat hunting", "3.14 System and Information Integrity"),
    ("3.14.7e", "Verify the correctness of security-critical or essential software, firmware, and hardware components using developer-provided tools, techniques, methods, and formal verification methodologies", "3.14 System and Information Integrity"),
]

emit_control_catalog(
    framework_id="nist-800-172",
    framework_name="NIST SP 800-172 — Enhanced Security Requirements for Protecting CUI",
    version="1.0 (Feb 2021)",
    source=NIST_PD_SOURCE + " — https://csrc.nist.gov/publications/detail/sp/800-172/final",
    families=sorted({fam for _, _, fam in NIST_800_172}),
    controls=_controls_from_tuples(NIST_800_172),
    tier="A",
)


# ---------------------------------------------------------------------------
# NIST AI Risk Management Framework 1.0 (2023)
# ---------------------------------------------------------------------------

NIST_AI_RMF = [
    # Govern (22 subcategories)
    ("GOVERN-1.1", "Legal and regulatory requirements involving AI are understood, managed, and documented", "Govern"),
    ("GOVERN-1.2", "The characteristics of trustworthy AI are integrated into organizational policies, processes, procedures, and practices", "Govern"),
    ("GOVERN-1.3", "Processes, procedures, and practices are in place to determine the needed level of risk management activities", "Govern"),
    ("GOVERN-1.4", "The risk management process and its outcomes are established through transparent policies, procedures, and other controls", "Govern"),
    ("GOVERN-1.5", "Ongoing monitoring and periodic review of the risk management process and its outcomes are planned and organizational roles and responsibilities clearly defined", "Govern"),
    ("GOVERN-1.6", "Mechanisms are in place to inventory AI systems and are resourced according to organizational risk priorities", "Govern"),
    ("GOVERN-1.7", "Processes and procedures are in place for decommissioning and phasing out AI systems safely", "Govern"),
    ("GOVERN-2.1", "Roles and responsibilities and lines of communication related to mapping, measuring, and managing AI risks are documented", "Govern"),
    ("GOVERN-2.2", "The organization's personnel and partners receive AI risk management training", "Govern"),
    ("GOVERN-2.3", "Executive leadership of the organization takes responsibility for decisions about risks associated with AI system development and deployment", "Govern"),
    ("GOVERN-3.1", "Decision-making related to mapping, measuring, and managing AI risks throughout the lifecycle is informed by a diverse team", "Govern"),
    ("GOVERN-3.2", "Policies and procedures are in place to define and differentiate roles and responsibilities for human-AI configurations and oversight", "Govern"),
    ("GOVERN-4.1", "Organizational policies and practices are in place to foster a critical thinking and safety-first mindset", "Govern"),
    ("GOVERN-4.2", "Organizational teams document the risks and potential impacts of the AI technology they design, develop, deploy, evaluate, and use", "Govern"),
    ("GOVERN-4.3", "Organizational practices are in place to enable AI testing, identification of incidents, and information sharing", "Govern"),
    ("GOVERN-5.1", "Organizational policies and practices are in place to collect, consider, prioritize, and integrate feedback from those external to the team that developed or deployed the AI system", "Govern"),
    ("GOVERN-5.2", "Mechanisms are established to enable the team that developed or deployed AI systems to regularly incorporate adjudicated feedback from relevant AI actors into system design and implementation", "Govern"),
    ("GOVERN-6.1", "Policies and procedures are in place that address AI risks associated with third-party entities", "Govern"),
    ("GOVERN-6.2", "Contingency processes are in place to handle failures or incidents in third-party data or AI systems deemed to be high-risk", "Govern"),
    # Map (12 subcategories)
    ("MAP-1.1", "Intended purposes, potentially beneficial uses, context-specific laws, norms and expectations, and prospective settings in which the AI system will be deployed are understood and documented", "Map"),
    ("MAP-1.2", "Inter-disciplinary AI actors, competencies, skills, and capacities for establishing context reflect demographic diversity and broad domain and user experience expertise", "Map"),
    ("MAP-1.3", "The organization's mission and relevant goals for AI technology are understood and documented", "Map"),
    ("MAP-1.4", "The business value or context of business use has been clearly defined or — in the case of assessing existing AI systems — re-evaluated", "Map"),
    ("MAP-1.5", "Organizational risk tolerances are determined and documented", "Map"),
    ("MAP-1.6", "System requirements are elicited from and understood by relevant AI actors", "Map"),
    ("MAP-2.1", "The specific tasks and methods used to implement the tasks that the AI system will support are defined", "Map"),
    ("MAP-2.2", "Information about the AI system's knowledge limits and how system output may be utilized and overseen by humans is documented", "Map"),
    ("MAP-2.3", "Scientific integrity and TEVV considerations are identified and documented, including those related to experimental design, data collection and selection, system trustworthiness, and construct validation", "Map"),
    ("MAP-3.1", "Potential benefits of intended AI system functionality and performance are examined and documented", "Map"),
    ("MAP-3.2", "Potential costs, including non-monetary costs, which result from expected or realized AI errors or system functionality and trustworthiness are examined and documented", "Map"),
    ("MAP-3.3", "Targeted application scope is specified and documented based on the system's capability, established context, and AI system categorization", "Map"),
    ("MAP-3.4", "Processes for operator and practitioner proficiency with AI system performance and trustworthiness — and relevant technical standards and certifications — are defined", "Map"),
    ("MAP-3.5", "Processes for human oversight are defined, assessed, and documented in accordance with organizational policies", "Map"),
    ("MAP-4.1", "Approaches for mapping AI technology and legal risks of its components — including the use of third-party data or software — are in place, followed, and documented", "Map"),
    ("MAP-4.2", "Internal risk controls for components of the AI system, including third-party AI technologies, are identified and documented", "Map"),
    ("MAP-5.1", "Likelihood and magnitude of each identified impact (both potentially beneficial and harmful) based on expected use, past uses of AI systems in similar contexts, public incident reports, feedback from those external to the team that developed or deployed the AI system, or other data are identified and documented", "Map"),
    ("MAP-5.2", "Practices and personnel for supporting regular engagement with relevant AI actors and integrating feedback about positive, negative, and unanticipated impacts are in place and documented", "Map"),
    # Measure (12 subcategories)
    ("MEASURE-1.1", "Approaches and metrics for measurement of AI risks enumerated during the MAP function are selected for implementation", "Measure"),
    ("MEASURE-1.2", "Appropriateness of AI metrics and effectiveness of existing controls are regularly assessed and updated", "Measure"),
    ("MEASURE-1.3", "Internal experts who did not serve as front-line developers for the system and/or independent assessors are involved in regular assessments and updates", "Measure"),
    ("MEASURE-2.1", "Test sets, metrics, and details about the tools used during TEVV are documented", "Measure"),
    ("MEASURE-2.2", "Evaluations involving human subjects meet applicable requirements — including human subject protection — and are representative of the relevant population", "Measure"),
    ("MEASURE-2.3", "AI system performance or assurance criteria are measured qualitatively or quantitatively and demonstrated for conditions similar to deployment setting(s)", "Measure"),
    ("MEASURE-2.4", "The functionality and behavior of the AI system and its components — as identified in the MAP function — are monitored when in production", "Measure"),
    ("MEASURE-2.5", "The AI system to be deployed is demonstrated to be valid and reliable", "Measure"),
    ("MEASURE-2.6", "The AI system is evaluated regularly for safety risks", "Measure"),
    ("MEASURE-2.7", "AI system security and resilience — as identified in the MAP function — are evaluated and documented", "Measure"),
    ("MEASURE-2.8", "Risks associated with transparency and accountability — as identified in the MAP function — are examined and documented", "Measure"),
    ("MEASURE-2.9", "The AI model is explained, validated, and documented, and AI system output is interpreted within its context — as identified in the MAP function — to inform responsible use and governance", "Measure"),
    ("MEASURE-2.10", "Privacy risk of the AI system — as identified in the MAP function — is examined and documented", "Measure"),
    ("MEASURE-2.11", "Fairness and bias — as identified in the MAP function — are evaluated and results are documented", "Measure"),
    ("MEASURE-2.12", "Environmental impact and sustainability of AI model training and management activities — as identified in the MAP function — are assessed and documented", "Measure"),
    ("MEASURE-2.13", "Effectiveness of the employed TEVV metrics and processes in the MEASURE function are evaluated and documented", "Measure"),
    ("MEASURE-3.1", "Approaches, personnel, and documentation are in place to regularly identify and track existing, unanticipated, and emergent AI risks based on factors such as intended and actual performance in deployed contexts", "Measure"),
    ("MEASURE-3.2", "Risk tracking approaches are considered for settings where AI risks are difficult to assess using currently available measurement techniques or where metrics are not yet available", "Measure"),
    ("MEASURE-3.3", "Feedback processes for end users and impacted communities to report problems and appeal system outcomes are established and integrated into AI system evaluation metrics", "Measure"),
    ("MEASURE-4.1", "Measurement approaches for identifying AI risks are connected to deployment context(s) and informed through consultation with domain experts and other end users", "Measure"),
    ("MEASURE-4.2", "Measurement results regarding AI system trustworthiness in deployment context(s) and across the AI lifecycle are informed by input from domain experts and relevant AI actors to validate whether the system is performing consistently as intended", "Measure"),
    ("MEASURE-4.3", "Measurable performance improvements or declines based on consultations with relevant AI actors, including affected communities, and field data about context-relevant risks and trustworthiness characteristics are identified and documented", "Measure"),
    # Manage (13 subcategories)
    ("MANAGE-1.1", "A determination is made as to whether the AI system achieves its intended purpose and stated objectives and whether its development or deployment should proceed", "Manage"),
    ("MANAGE-1.2", "Treatment of documented AI risks is prioritized based on impact, likelihood, and available resources or methods", "Manage"),
    ("MANAGE-1.3", "Responses to the AI risks deemed high priority — as identified by the MAP function — are developed, planned, and documented", "Manage"),
    ("MANAGE-1.4", "Negative residual risks (defined as the sum of all unmitigated risks) to both downstream acquirers of AI systems and end users are documented", "Manage"),
    ("MANAGE-2.1", "Resources required to manage AI risks are taken into account, along with viable non-AI alternative systems, approaches, or methods to reduce the magnitude or likelihood of potential impacts", "Manage"),
    ("MANAGE-2.2", "Mechanisms are in place and applied to sustain the value of deployed AI systems", "Manage"),
    ("MANAGE-2.3", "Procedures are followed to respond to and recover from a previously unknown risk when it is identified", "Manage"),
    ("MANAGE-2.4", "Mechanisms are in place and applied, and responsibilities are assigned and understood, to supersede, disengage, or deactivate AI systems that demonstrate performance or outcomes inconsistent with intended use", "Manage"),
    ("MANAGE-3.1", "AI risks and benefits from third-party resources are regularly monitored, and risk controls are applied and documented", "Manage"),
    ("MANAGE-3.2", "Pre-trained models which are used for development are monitored as part of AI system regular monitoring and maintenance", "Manage"),
    ("MANAGE-4.1", "Post-deployment AI system monitoring plans are implemented, including mechanisms for capturing and evaluating input from users and other relevant AI actors, appeal and override, decommissioning, incident response, recovery, and change management", "Manage"),
    ("MANAGE-4.2", "Measurable activities for continual improvements are integrated into AI system updates and include regular engagement with interested parties, including relevant AI actors", "Manage"),
    ("MANAGE-4.3", "Incidents and errors are communicated to relevant AI actors, including affected communities. Processes for tracking, responding to, and recovering from incidents and errors are followed and documented", "Manage"),
]

emit_control_catalog(
    framework_id="nist-ai-rmf-1.0",
    framework_name="NIST AI Risk Management Framework 1.0",
    version="1.0 (Jan 2023)",
    source=NIST_PD_SOURCE + " — https://www.nist.gov/itl/ai-risk-management-framework",
    families=["Govern", "Map", "Measure", "Manage"],
    controls=_controls_from_tuples(NIST_AI_RMF),
    tier="A",
)


# ---------------------------------------------------------------------------
# NIST Privacy Framework 1.0 (2020)
# ---------------------------------------------------------------------------

NIST_PRIVACY_FRAMEWORK = [
    ("ID.IM-P1", "Systems/products/services that process data are inventoried", "Identify-P (ID-P)"),
    ("ID.IM-P2", "Owners or operators (e.g., the organization or third parties such as service providers, partners, customers, and developers) and their roles with respect to the systems/products/services and components (e.g., internal or external) that process data are inventoried", "Identify-P (ID-P)"),
    ("ID.IM-P3", "Categories of individuals (e.g., customers, employees or prospective employees, consumers) whose data are being processed are inventoried", "Identify-P (ID-P)"),
    ("ID.IM-P4", "Data actions of the systems/products/services are inventoried", "Identify-P (ID-P)"),
    ("ID.IM-P5", "The purposes for the data actions are inventoried", "Identify-P (ID-P)"),
    ("ID.IM-P6", "Data elements within the data actions are inventoried", "Identify-P (ID-P)"),
    ("ID.IM-P7", "The data processing environment is identified (e.g., geographic location, internal, cloud, third parties)", "Identify-P (ID-P)"),
    ("ID.IM-P8", "Data processing is mapped, illustrating the data actions and associated data elements for systems/products/services, including components; roles of the component owners/operators; and interactions of individuals or third parties with the systems/products/services", "Identify-P (ID-P)"),
    ("ID.BE-P1", "The organization's role(s) in the data processing ecosystem are identified and communicated", "Identify-P (ID-P)"),
    ("ID.BE-P2", "Priorities for organizational mission, objectives, and activities are established and communicated", "Identify-P (ID-P)"),
    ("ID.BE-P3", "Systems/products/services that support organizational priorities are identified and key requirements communicated", "Identify-P (ID-P)"),
    ("ID.RA-P1", "Contextual factors related to the systems/products/services and the data actions are identified (e.g., individuals' demographics and privacy interests or perceptions, data sensitivity and/or types, visibility of data processing to individuals and third parties)", "Identify-P (ID-P)"),
    ("ID.RA-P2", "Data analytic inputs and outputs are identified and evaluated for bias", "Identify-P (ID-P)"),
    ("ID.RA-P3", "Potential problematic data actions and associated problems are identified", "Identify-P (ID-P)"),
    ("ID.RA-P4", "Problematic data actions, likelihoods, and impacts are used to determine and prioritize risk", "Identify-P (ID-P)"),
    ("ID.RA-P5", "Risk responses are identified, prioritized, and implemented", "Identify-P (ID-P)"),
    ("ID.DE-P1", "Data processing ecosystem risk management policies, processes, and procedures are identified, established, assessed, managed, and agreed to by organizational stakeholders", "Identify-P (ID-P)"),
    ("ID.DE-P2", "Data processing ecosystem parties (e.g., service providers, customers, partners, product manufacturers, application developers) are identified, prioritized, and assessed using a privacy risk assessment process", "Identify-P (ID-P)"),
    ("ID.DE-P3", "Contracts with data processing ecosystem parties are used to implement appropriate measures designed to meet the objectives of an organization's privacy program", "Identify-P (ID-P)"),
    ("ID.DE-P4", "Interoperability frameworks or similar multi-party approaches are used to manage data processing ecosystem privacy risks", "Identify-P (ID-P)"),
    ("ID.DE-P5", "Data processing ecosystem parties are routinely assessed using audits, test results, or other forms of evaluations to confirm they are meeting their contractual, interoperability framework, or other obligations", "Identify-P (ID-P)"),
    ("GV.PO-P1", "Organizational privacy values and policies (e.g., conditions on data processing such as data uses or retention periods, individuals' prerogatives with respect to data processing) are established and communicated", "Govern-P (GV-P)"),
    ("GV.PO-P2", "Processes to instill organizational privacy values within system/product/service development and operations are established and in place", "Govern-P (GV-P)"),
    ("GV.PO-P3", "Roles and responsibilities for the workforce are established with respect to privacy", "Govern-P (GV-P)"),
    ("GV.PO-P4", "Privacy roles and responsibilities are coordinated and aligned with third-party stakeholders (e.g., service providers, customers, partners)", "Govern-P (GV-P)"),
    ("GV.PO-P5", "Legal, regulatory, and contractual requirements regarding privacy are understood and managed", "Govern-P (GV-P)"),
    ("GV.PO-P6", "Governance and risk management policies, processes, and procedures address privacy risks", "Govern-P (GV-P)"),
    ("GV.RM-P1", "Risk management processes are established, managed, and agreed to by organizational stakeholders", "Govern-P (GV-P)"),
    ("GV.RM-P2", "Organizational risk tolerance is determined and clearly expressed", "Govern-P (GV-P)"),
    ("GV.RM-P3", "The organization's determination of risk tolerance is informed by its role(s) in the data processing ecosystem", "Govern-P (GV-P)"),
    ("GV.AT-P1", "The workforce is informed and trained on its roles and responsibilities", "Govern-P (GV-P)"),
    ("GV.AT-P2", "Senior executives understand their roles and responsibilities", "Govern-P (GV-P)"),
    ("GV.AT-P3", "Privacy personnel understand their roles and responsibilities", "Govern-P (GV-P)"),
    ("GV.AT-P4", "Third parties (e.g., service providers, customers, partners) understand their roles and responsibilities", "Govern-P (GV-P)"),
    ("GV.MT-P1", "Privacy risk is re-evaluated on an ongoing basis and as key factors — including the organization's business environment (e.g., introduction of new technologies), governance (e.g., legal obligations, risk tolerance), data processing, and systems/products/services — change", "Govern-P (GV-P)"),
    ("GV.MT-P2", "Privacy values, policies, and training are reviewed, and any updates are communicated", "Govern-P (GV-P)"),
    ("GV.MT-P3", "Policies, processes, and procedures for assessing compliance with legal requirements and privacy policies are established and in place", "Govern-P (GV-P)"),
    ("GV.MT-P4", "Policies, processes, and procedures for communicating progress on managing privacy risks are established and in place", "Govern-P (GV-P)"),
    ("GV.MT-P5", "Policies, processes, and procedures are established and in place to receive, analyze, and respond to problematic data actions disclosed to the organization from internal and external sources (e.g., internal discovery, privacy researchers, professional events)", "Govern-P (GV-P)"),
    ("GV.MT-P6", "Policies, processes, and procedures incorporate lessons learned from problematic data actions", "Govern-P (GV-P)"),
    ("GV.MT-P7", "Policies, processes, and procedures for receiving, tracking, and responding to complaints, concerns, and questions from individuals about organizational privacy practices are established and in place", "Govern-P (GV-P)"),
    ("CT.PO-P1", "Policies, processes, and procedures for authorizing data processing (e.g., organizational decisions, individual consent), revoking authorizations, and maintaining authorizations are established and in place", "Control-P (CT-P)"),
    ("CT.PO-P2", "Policies, processes, and procedures for enabling data review, transfer, sharing or disclosure, alteration, and deletion are established and in place (e.g., to maintain data quality, manage data retention)", "Control-P (CT-P)"),
    ("CT.PO-P3", "Policies, processes, and procedures for enabling individuals' data processing preferences and requests are established and in place", "Control-P (CT-P)"),
    ("CT.PO-P4", "A data life cycle to manage data is aligned and implemented with the system development life cycle to manage systems", "Control-P (CT-P)"),
    ("CT.DM-P1", "Data elements can be accessed for review", "Control-P (CT-P)"),
    ("CT.DM-P2", "Data elements can be accessed for transmission or disclosure", "Control-P (CT-P)"),
    ("CT.DM-P3", "Data elements can be accessed for alteration", "Control-P (CT-P)"),
    ("CT.DM-P4", "Data elements can be accessed for deletion", "Control-P (CT-P)"),
    ("CT.DM-P5", "Data are destroyed according to policy", "Control-P (CT-P)"),
    ("CT.DM-P6", "Data are transmitted using standardized formats", "Control-P (CT-P)"),
    ("CT.DM-P7", "Mechanisms for transmitting processing permissions and related data values with data elements are established and in place", "Control-P (CT-P)"),
    ("CT.DM-P8", "Audit/log records are determined, documented, implemented, and reviewed in accordance with policy and incorporating the principle of data minimization", "Control-P (CT-P)"),
    ("CT.DM-P9", "Technical measures implemented to manage data processing are tested and assessed", "Control-P (CT-P)"),
    ("CT.DM-P10", "Stakeholder privacy preferences are included in algorithmic design objectives and outputs are evaluated against these preferences", "Control-P (CT-P)"),
    ("CM.PO-P1", "Transparency policies, processes, and procedures for communicating data processing purposes, practices, and associated privacy risks are established and in place", "Communicate-P (CM-P)"),
    ("CM.PO-P2", "Roles and responsibilities for communicating with individuals are established", "Communicate-P (CM-P)"),
    ("CM.AW-P1", "Mechanisms (e.g., notices, internal or public reports) for communicating data processing purposes, practices, associated privacy risks, and options for enabling individuals' data processing preferences and requests are established and in place", "Communicate-P (CM-P)"),
    ("CM.AW-P2", "Mechanisms for obtaining feedback from individuals (e.g., surveys or focus groups) about data processing and associated privacy risks are established and in place", "Communicate-P (CM-P)"),
    ("CM.AW-P3", "System/product/service design enables data processing visibility", "Communicate-P (CM-P)"),
    ("CM.AW-P4", "Records of data disclosures and sharing are maintained and can be reviewed", "Communicate-P (CM-P)"),
    ("CM.AW-P5", "Data corrections or deletions can be communicated to individuals or organizations (e.g., data sources) in the data processing ecosystem", "Communicate-P (CM-P)"),
    ("CM.AW-P6", "Data provenance and lineage are maintained and can be reviewed", "Communicate-P (CM-P)"),
    ("CM.AW-P7", "Impacted individuals and organizations are notified about a privacy breach or event", "Communicate-P (CM-P)"),
    ("CM.AW-P8", "Individuals are provided with mitigation mechanisms (e.g., credit monitoring, consent withdrawal, data alteration or deletion) to address impacts of problematic data actions", "Communicate-P (CM-P)"),
    ("PR.PO-P1", "A baseline configuration of information technology is created and maintained incorporating security principles (e.g., concept of least functionality)", "Protect-P (PR-P)"),
    ("PR.PO-P2", "Configuration change control processes are established and in place", "Protect-P (PR-P)"),
    ("PR.PO-P3", "Backups of information are conducted, maintained, and tested", "Protect-P (PR-P)"),
    ("PR.PO-P4", "Policy and regulations regarding the physical operating environment for organizational assets are met", "Protect-P (PR-P)"),
    ("PR.PO-P5", "Protections against data leaks are implemented", "Protect-P (PR-P)"),
    ("PR.PO-P6", "Data are destroyed according to policy", "Protect-P (PR-P)"),
    ("PR.PO-P7", "Policies, processes, and procedures are maintained and used to manage the protection of data", "Protect-P (PR-P)"),
    ("PR.PO-P8", "Response plans (Incident Response and Business Continuity) and recovery plans (Incident Recovery and Disaster Recovery) are established, in place, and managed", "Protect-P (PR-P)"),
    ("PR.PO-P9", "Response and recovery plans are tested", "Protect-P (PR-P)"),
    ("PR.PO-P10", "A privacy-aware software development life cycle (SDLC) including technology development practices is implemented", "Protect-P (PR-P)"),
    ("PR.PO-P11", "A vulnerability management plan is developed and implemented", "Protect-P (PR-P)"),
    ("PR.AC-P1", "Identities and credentials are issued, managed, verified, revoked, and audited for authorized individuals, processes, and devices", "Protect-P (PR-P)"),
    ("PR.AC-P2", "Physical access to data and devices is managed", "Protect-P (PR-P)"),
    ("PR.AC-P3", "Remote access is managed", "Protect-P (PR-P)"),
    ("PR.AC-P4", "Access permissions and authorizations are managed, incorporating the principles of least privilege and separation of duties", "Protect-P (PR-P)"),
    ("PR.AC-P5", "Network integrity is protected (e.g., network segregation, network segmentation)", "Protect-P (PR-P)"),
    ("PR.AC-P6", "Individuals and devices are proofed and bound to credentials, and authenticated commensurate with the risk of the transaction (e.g., individuals' security and privacy risks and other organizational risks)", "Protect-P (PR-P)"),
    ("PR.DS-P1", "Data-at-rest are protected", "Protect-P (PR-P)"),
    ("PR.DS-P2", "Data-in-transit are protected", "Protect-P (PR-P)"),
    ("PR.DS-P3", "Systems/products/services and associated data are formally managed throughout removal, transfers, and disposition", "Protect-P (PR-P)"),
    ("PR.DS-P4", "Adequate capacity to ensure availability is maintained", "Protect-P (PR-P)"),
    ("PR.DS-P5", "Protections against data leaks are implemented", "Protect-P (PR-P)"),
    ("PR.DS-P6", "Integrity checking mechanisms are used to verify software, firmware, and information integrity", "Protect-P (PR-P)"),
    ("PR.DS-P7", "The development and testing environments are separate from the production environment", "Protect-P (PR-P)"),
    ("PR.DS-P8", "Integrity checking mechanisms are used to verify hardware integrity", "Protect-P (PR-P)"),
    ("PR.MA-P1", "Maintenance and repair of organizational assets are performed and logged, with approved and controlled tools", "Protect-P (PR-P)"),
    ("PR.MA-P2", "Remote maintenance of organizational assets is approved, logged, and performed in a manner that prevents unauthorized access", "Protect-P (PR-P)"),
    ("PR.PT-P1", "Removable media is protected and its use restricted according to policy", "Protect-P (PR-P)"),
    ("PR.PT-P2", "The principle of least functionality is incorporated by configuring systems to provide only essential capabilities", "Protect-P (PR-P)"),
    ("PR.PT-P3", "Communications and control networks are protected", "Protect-P (PR-P)"),
    ("PR.PT-P4", "Mechanisms (e.g., failsafe, load balancing, hot swap) are implemented to achieve resilience requirements in normal and adverse situations", "Protect-P (PR-P)"),
]

emit_control_catalog(
    framework_id="nist-privacy-framework-1.0",
    framework_name="NIST Privacy Framework 1.0",
    version="1.0 (Jan 2020)",
    source=NIST_PD_SOURCE + " — https://www.nist.gov/privacy-framework",
    families=["Identify-P (ID-P)", "Govern-P (GV-P)", "Control-P (CT-P)", "Communicate-P (CM-P)", "Protect-P (PR-P)"],
    controls=_controls_from_tuples(NIST_PRIVACY_FRAMEWORK),
    tier="A",
)


# ---------------------------------------------------------------------------
# NIST SSDF (Secure Software Development Framework) SP 800-218
# ---------------------------------------------------------------------------

NIST_SSDF = [
    ("PO.1.1", "Identify and document all security requirements for the organization's software development infrastructures and processes", "Prepare the Organization (PO)"),
    ("PO.1.2", "Identify and document all security requirements for organization-developed software to meet, and maintain the requirements over time", "Prepare the Organization (PO)"),
    ("PO.1.3", "Communicate requirements to all third parties who will provide commercial software components for reuse by the organization's own software", "Prepare the Organization (PO)"),
    ("PO.2.1", "Create new roles and alter responsibilities for existing roles as needed to encompass all parts of the SSDF", "Prepare the Organization (PO)"),
    ("PO.2.2", "Provide role-based training for all personnel with responsibilities that contribute to secure development", "Prepare the Organization (PO)"),
    ("PO.2.3", "Obtain upper management or authorizing official commitment to secure development, and convey that commitment to all with development-related roles and responsibilities", "Prepare the Organization (PO)"),
    ("PO.3.1", "Specify which tools or tool types must or should be included in each toolchain", "Prepare the Organization (PO)"),
    ("PO.3.2", "Follow recommended security practices to deploy, operate, and maintain tools and toolchains", "Prepare the Organization (PO)"),
    ("PO.3.3", "Configure tools to generate artifacts of their support of secure software development practices as defined by the organization", "Prepare the Organization (PO)"),
    ("PO.4.1", "Define criteria for software security checks and track throughout the SDLC", "Prepare the Organization (PO)"),
    ("PO.4.2", "Implement processes, mechanisms, etc. to gather and safeguard the necessary information in support of the criteria", "Prepare the Organization (PO)"),
    ("PO.5.1", "Separate and protect each environment involved in software development", "Prepare the Organization (PO)"),
    ("PO.5.2", "Secure and harden development endpoints (i.e., endpoints for software designers, developers, testers, builders, etc.) to perform development-related tasks using a risk-based approach", "Prepare the Organization (PO)"),
    ("PS.1.1", "Store all forms of code — including source code, executable code, and configuration-as-code — based on the principle of least privilege so that only authorized personnel, tools, services, etc. have access", "Protect the Software (PS)"),
    ("PS.2.1", "Make software integrity verification information available to software acquirers", "Protect the Software (PS)"),
    ("PS.3.1", "Securely archive the necessary files and supporting data (e.g., integrity verification information, provenance data) to be retained for each software release", "Protect the Software (PS)"),
    ("PS.3.2", "Collect, safeguard, maintain, and share provenance data for all components of each software release", "Protect the Software (PS)"),
    ("PW.1.1", "Use forms of risk modeling — such as threat modeling, attack modeling, or attack surface mapping — to help assess the security risk for the software", "Produce Well-Secured Software (PW)"),
    ("PW.1.2", "Track and maintain the software's security requirements, risks, and design decisions", "Produce Well-Secured Software (PW)"),
    ("PW.1.3", "Where appropriate, build in support for using standardized security features and services (e.g., enabling system logging for security events to help with incident detection, using standardized log formats) instead of creating proprietary implementations of security features and services", "Produce Well-Secured Software (PW)"),
    ("PW.2.1", "Have a qualified person (or people) who were not involved with the design review the software design to confirm that it meets all of the security requirements and satisfactorily addresses the identified risk information", "Produce Well-Secured Software (PW)"),
    ("PW.4.1", "Acquire and maintain well-secured software components (e.g., software libraries, modules, middleware, frameworks) from commercial, open source, and other third-party developers for use by the organization's software", "Produce Well-Secured Software (PW)"),
    ("PW.4.2", "Create and maintain well-secured software components in-house following SDLC processes to meet common internal software development needs that cannot be better met by third-party software components", "Produce Well-Secured Software (PW)"),
    ("PW.4.4", "Verify that acquired commercial, open-source, and all other third-party software components comply with the requirements — as defined by the organization — throughout their life cycles", "Produce Well-Secured Software (PW)"),
    ("PW.5.1", "Follow all secure coding practices that are appropriate to the development languages and environment to meet the organization's requirements", "Produce Well-Secured Software (PW)"),
    ("PW.6.1", "Use compiler, interpreter, and build tools that offer features to improve executable security", "Produce Well-Secured Software (PW)"),
    ("PW.6.2", "Determine which compiler, interpreter, and build tool features should be used and how each should be configured, then implement and use the approved configurations", "Produce Well-Secured Software (PW)"),
    ("PW.7.1", "Determine whether code review (a person directly looks at the code to find issues) and/or code analysis (tools are used to find issues in code, either in a fully automated way or in conjunction with a person) should be used, as defined by the organization", "Produce Well-Secured Software (PW)"),
    ("PW.7.2", "Perform the code review and/or code analysis based on the organization's secure coding standards, and document and triage all discovered issues and recommended remediations in the development team's workflow or issue tracking system", "Produce Well-Secured Software (PW)"),
    ("PW.8.1", "Determine whether executable code testing should be performed to find vulnerabilities not already found by previous reviews, analyses, and testing and, if so, which types of testing should be used", "Produce Well-Secured Software (PW)"),
    ("PW.8.2", "Scope the testing, design the tests, perform the testing, and document the results, including documenting and triaging all discovered issues and recommended remediations in the development team's workflow or issue tracking system", "Produce Well-Secured Software (PW)"),
    ("PW.9.1", "Define a core set of secure settings, and ensure that it is the default configuration", "Produce Well-Secured Software (PW)"),
    ("PW.9.2", "Implement the default settings (or groups of default settings, if applicable), document each setting for software administrators, and explain how to operate and use the default settings", "Produce Well-Secured Software (PW)"),
    ("RV.1.1", "Gather information from software acquirers, users, and public sources on potential vulnerabilities in the software and third-party components that the software uses, and investigate all credible reports", "Respond to Vulnerabilities (RV)"),
    ("RV.1.2", "Review, analyze, and/or test the software's code to identify or confirm the presence of previously undetected vulnerabilities", "Respond to Vulnerabilities (RV)"),
    ("RV.1.3", "Have a policy that addresses vulnerability disclosure and remediation, and implement the roles, responsibilities, and processes needed to support that policy", "Respond to Vulnerabilities (RV)"),
    ("RV.2.1", "Analyze each vulnerability to gather sufficient information about risk to plan its remediation or other risk response", "Respond to Vulnerabilities (RV)"),
    ("RV.2.2", "Plan and implement risk responses for vulnerabilities", "Respond to Vulnerabilities (RV)"),
    ("RV.3.1", "Analyze identified vulnerabilities to determine their root causes", "Respond to Vulnerabilities (RV)"),
    ("RV.3.2", "Analyze the root causes over time to identify patterns, such as a particular secure coding practice not being followed consistently", "Respond to Vulnerabilities (RV)"),
    ("RV.3.3", "Review the software for similar vulnerabilities to eradicate a class of vulnerabilities, and proactively fix them rather than waiting for external reports", "Respond to Vulnerabilities (RV)"),
    ("RV.3.4", "Review the SDLC process and update it if appropriate to prevent the cause of similar vulnerabilities in the future", "Respond to Vulnerabilities (RV)"),
]

emit_control_catalog(
    framework_id="nist-ssdf-800-218",
    framework_name="NIST SP 800-218 Secure Software Development Framework (SSDF)",
    version="1.1 (Feb 2022)",
    source=NIST_PD_SOURCE + " — https://csrc.nist.gov/publications/detail/sp/800-218/final",
    families=["Prepare the Organization (PO)", "Protect the Software (PS)", "Produce Well-Secured Software (PW)", "Respond to Vulnerabilities (RV)"],
    controls=_controls_from_tuples(NIST_SSDF),
    tier="A",
)


if __name__ == "__main__":
    print("Generated NIST family catalogs.")
