"""Regenerate frameworks.yaml by scanning bundled catalog JSONs on disk.

This makes the manifest truthful by construction — the contents of
data/<tier>/ ARE the manifest. No hand-maintained sync required.

Run this script whenever catalogs are added/removed/modified.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

from _generators import DATA_ROOT  # type: ignore[import-not-found]


TIER_DIRS: dict[str, tuple[str, str]] = {
    # dir_name: (default_tier_guess, default_category_guess)
    "us-federal": ("A", "control"),
    "international": ("A", "control"),
    "state-privacy": ("D", "obligation"),
    "stubs": ("C", "control"),
    "threats": ("B", "technique"),
}

# Preferred ordering to keep the YAML readable
TIER_ORDER = ["us-federal", "international", "state-privacy", "threats", "stubs"]


def infer_refresh(tier: str, category: str) -> str:
    """Best-guess refresh cadence based on tier and category."""
    if category in ("vulnerability",):
        return "daily"
    if category in ("technique",):
        return "weekly"
    if tier == "A":
        return "monthly"
    if tier == "D":
        return "monthly"  # watch statute updates
    return "manual"


def scan_dir(subdir: str) -> list[dict]:
    """Return manifest entries for all JSON catalogs in DATA_ROOT/subdir."""
    dir_path = DATA_ROOT / subdir
    if not dir_path.exists():
        return []
    tier_default, category_default = TIER_DIRS[subdir]
    entries: list[dict] = []

    for path in sorted(dir_path.glob("*.json")):
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as exc:
            # Surface the skip explicitly (stderr, not stdout, so it
            # doesn't pollute the manifest summary going to a pipe).
            # Silent drops would otherwise produce a smaller frameworks.yaml
            # that only the catalog-refresh.yml workflow's pytest step
            # would notice (via test_all_bundled.py's count assertion) —
            # devs running the script locally see nothing without this.
            print(
                f"WARN: skipped malformed catalog file {path}: {exc!r}",
                file=sys.stderr,
            )
            continue

        entry = {
            "id": data.get("framework_id", path.stem),
            "name": data.get("framework_name", path.stem),
            "version": data.get("version", "unknown"),
            "tier": data.get("tier", tier_default),
            "category": data.get("category", category_default),
            "path": f"{subdir}/{path.name}",
        }
        # Optional fields — only emit when present so YAML stays readable
        for src_field, dst_field in [
            ("source", "source_url"),
            ("license_terms", "license"),
            ("license_url", "license_url"),
        ]:
            val = data.get(src_field)
            if val:
                entry[dst_field] = val
        if data.get("license_required"):
            entry["license_required"] = True
        if data.get("placeholder"):
            entry["placeholder"] = True
        entry["refresh"] = infer_refresh(entry["tier"], entry["category"])
        entries.append(entry)

    return entries


def main() -> None:
    all_entries: list[dict] = []
    for subdir in TIER_ORDER:
        all_entries.extend(scan_dir(subdir))

    manifest = {
        "version": 1,
        "frameworks": all_entries,
    }

    out_path = DATA_ROOT / "frameworks.yaml"

    # Write the YAML with a header comment preserved
    header = """# Evidentia framework manifest — single source of truth for bundled catalogs.
#
# GENERATED BY scripts/catalogs/regenerate_manifest.py — do not hand-edit.
# To add/remove a framework: change the JSON in data/<tier-dir>/ then re-run the
# regeneration script. The manifest reflects what is on disk.
#
# Schema is validated by evidentia_core.catalogs.manifest.FrameworkManifest.
# Fields:
#   id            Canonical framework ID (kebab-case; stable across versions).
#   name          Human-readable name shown in `catalog list`.
#   version       Framework version string.
#   tier          A | B | C | D — redistribution tier (see ATTRIBUTION.md).
#   category      control | technique | vulnerability | obligation.
#   path          JSON path relative to data/ directory.
#   source_url    Upstream URL.
#   license       Short license statement.
#   license_required  true if control text is copyrighted (Tier C stub).
#   license_url   URL where users can license/download authoritative text.
#   placeholder   true if this catalog is a stub (no authoritative text).
#   refresh       Adapter schedule: daily | weekly | monthly | manual.

"""
    # width=200 pins PyYAML's word-wrap behavior so the regenerated
    # frameworks.yaml is byte-stable across PyYAML versions and
    # platform locales. The default (width=80) silently re-wraps long
    # license: strings on different column boundaries depending on
    # PyYAML's exact version, producing whitespace-only diffs that
    # the catalog-refresh.yml workflow flagged as drift (issues #1-#4
    # at v0.7.1 ship time). 200 keeps lines readable while reducing
    # wrap-induced churn for the SOC 2 / ISO 27001 / similar long
    # license-disclaimer strings.
    body = yaml.safe_dump(
        manifest,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=200,
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(body)

    print(f"Wrote manifest with {len(all_entries)} frameworks to {out_path}")
    by_tier: dict[str, int] = {}
    for e in all_entries:
        by_tier[e["tier"]] = by_tier.get(e["tier"], 0) + 1
    for tier in sorted(by_tier):
        print(f"  Tier {tier}: {by_tier[tier]}")


if __name__ == "__main__":
    main()
