"""Risk statement models following NIST SP 800-30 structure.

Risk statements are generated by the AI module based on identified gaps
and system context. Each statement includes structured threat analysis,
likelihood/impact ratings, and remediation recommendations.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import Field

from evidentia_core.audit.provenance import GenerationContext
from evidentia_core.models.common import (
    EvidentiaModel,
    current_version,
    new_id,
    utc_now,
)


class RiskLevel(str, Enum):
    """Overall risk level (derived from likelihood × impact)."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFORMATIONAL = "informational"


class LikelihoodRating(str, Enum):
    """Likelihood that a threat event will occur (NIST SP 800-30 scale)."""

    VERY_HIGH = "very_high"
    HIGH = "high"
    MODERATE = "moderate"
    LOW = "low"
    VERY_LOW = "very_low"


class ImpactRating(str, Enum):
    """Impact if the threat event occurs (NIST SP 800-30 scale)."""

    VERY_HIGH = "very_high"
    HIGH = "high"
    MODERATE = "moderate"
    LOW = "low"
    VERY_LOW = "very_low"


class RiskTreatment(str, Enum):
    """Risk treatment decision."""

    MITIGATE = "mitigate"
    ACCEPT = "accept"
    TRANSFER = "transfer"
    AVOID = "avoid"
    PENDING = "pending"


class TraceClaim(EvidentiaModel):
    """A single claim within a Policy Reasoning Trace (v0.8.0 P0.2).

    Per arXiv 2509.23291, a reasoning trace decomposes the
    AI-generated artifact into ordered atomic claims, each
    pointing back to the policy clauses (catalog control IDs,
    OCC bulletin paragraphs, etc.) that justify it. Lets a
    3PAO / federal SI auditor verify the LLM's reasoning chain
    rather than treating the output as an opaque blob.
    """

    claim: str = Field(
        description=(
            "A single atomic claim from the AI-generated "
            "artifact. Should be self-contained — interpretable "
            "without needing to re-read the surrounding text."
        ),
    )
    clause_citations: list[str] = Field(
        default_factory=list,
        description=(
            "Policy clauses that justify the claim. Format is "
            "free-form but recommended convention is "
            "``<framework_id>:<control_id>`` (e.g., "
            "``nist-800-53-rev5-moderate:AC-2``) for catalog "
            "controls, or ``<source>:<section>`` (e.g., "
            "``occ-2026-13a:III.A.4``) for regulatory "
            "publications. May be empty for foundational "
            "claims (assertions about the system context that "
            "don't require external citation)."
        ),
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description=(
            "Self-reported confidence that the claim is "
            "supportable by the cited clauses. 1.0 = highly "
            "confident; 0.0 = fully uncertain. Auditors should "
            "treat this as a hint, not authoritative — the "
            "value reflects the LLM's introspection, not "
            "objective truth."
        ),
    )


class ReasoningTrace(EvidentiaModel):
    """Policy Reasoning Trace for an AI-generated artifact (v0.8.0 P0.2).

    Per arXiv 2509.23291. A structured decomposition of the
    artifact's claims + per-claim clause citations + confidence
    scores. Auditor-defensible because the LLM's reasoning
    chain is exposed for review rather than buried inside the
    final text.

    The trace lives as an optional field on artifacts that
    benefit from PRT (currently :class:`RiskStatement`; future
    artifacts: plain-English explanations, threat models,
    OSCAL component-definition narratives). When present, OSCAL
    emit surfaces the trace in back-matter as an Evidentia-
    namespaced resource so trestle-conformance round-trips
    preserve it.
    """

    claims: list[TraceClaim] = Field(
        description=(
            "Ordered list of atomic claims composing the AI "
            "artifact. The order is rhetorical — claim N may "
            "build on claim N-1 — so reordering is not safe."
        ),
    )
    methodology: str = Field(
        default="",
        description=(
            "Short note describing how the LLM was instructed "
            "to decompose its output into claims. Useful for "
            "auditors comparing traces across model versions / "
            "prompt revisions. Optional (empty string when the "
            "trace was authored without a documented methodology)."
        ),
    )
    overall_confidence: float = Field(
        ge=0.0,
        le=1.0,
        default=0.0,
        description=(
            "Self-reported confidence across the entire trace, "
            "typically the geometric mean of per-claim "
            "confidences. Provided for fast filtering — "
            "auditors looking for low-confidence traces don't "
            "have to aggregate across claims."
        ),
    )


class RiskStatement(EvidentiaModel):
    """A structured risk statement following NIST SP 800-30 Rev 1 format.

    The structure follows the NIST risk equation:
    Risk = Likelihood(Threat × Vulnerability) × Impact
    """

    id: str = Field(default_factory=new_id)
    # ── Core NIST SP 800-30 risk statement components ──────────────────
    asset: str = Field(
        description="The system, data, function, or process at risk",
    )
    threat_source: str = Field(
        description="Who or what could exploit the vulnerability",
    )
    threat_event: str = Field(
        description="What the threat source would do",
    )
    vulnerability: str = Field(
        description="The specific weakness that enables the threat",
    )
    predisposing_conditions: list[str] = Field(
        default_factory=list,
        description="Environmental factors that increase likelihood",
    )
    # ── Ratings ────────────────────────────────────────────────────────
    likelihood: LikelihoodRating = Field(
        description="Likelihood that the threat event will occur",
    )
    likelihood_rationale: str = Field(
        description="Specific explanation for the likelihood rating",
    )
    impact: ImpactRating = Field(
        description="Impact if the threat event occurs",
    )
    impact_rationale: str = Field(
        description="Specific explanation for the impact rating",
    )
    risk_level: RiskLevel = Field(
        description="Overall risk level derived from likelihood × impact",
    )
    risk_description: str = Field(
        description="Full prose risk statement combining all components",
    )
    # ── Remediation ────────────────────────────────────────────────────
    recommended_controls: list[str] = Field(
        description="NIST 800-53 control IDs that would mitigate this risk",
    )
    remediation_priority: int = Field(
        ge=1,
        le=5,
        description="1 = most urgent, 5 = least urgent",
    )
    remediation_steps: list[str] = Field(
        default_factory=list,
        description="Ordered list of specific remediation actions",
    )
    estimated_remediation_effort: str | None = Field(
        default=None,
        description="Estimated effort: 'hours', 'days', 'weeks', 'months'",
    )
    # ── Treatment ──────────────────────────────────────────────────────
    treatment: RiskTreatment = Field(
        default=RiskTreatment.PENDING,
        description="Risk treatment decision",
    )
    treatment_rationale: str | None = Field(
        default=None,
        description="Rationale for the treatment decision (required if accepted)",
    )
    # ── Lifecycle ──────────────────────────────────────────────────────
    generated_by: str = Field(
        default="evidentia-ai",
        description="'evidentia-ai' for generated, or user email for manual",
    )
    generated_at: datetime = Field(default_factory=utc_now)
    model_used: str | None = Field(
        default=None,
        description="LLM model used for generation",
    )
    generation_context: GenerationContext | None = Field(
        default=None,
        description=(
            "v0.7.1+ AI provenance block — model, temperature, prompt_hash, "
            "run_id, attempts. Optional to preserve deserialization compat "
            "with pre-v0.7.1 RiskStatement payloads. The v0.8 target once "
            "planned for tightening to required has passed without action; "
            "no deprecation is currently scheduled — the field stays "
            "optional until cached payloads age out, after which a v1.0 "
            "cycle may revisit the tightening. "
            "See ``evidentia_core.audit.provenance.GenerationContext``."
        ),
    )
    reviewed_by: str | None = Field(default=None)
    reviewed_at: datetime | None = Field(default=None)
    accepted: bool = Field(
        default=False,
        description="Whether this risk statement has been accepted by a reviewer",
    )
    # ── Mappings ───────────────────────────────────────────────────────
    source_gap_id: str | None = Field(
        default=None,
        description="ID of the ControlGap that triggered this risk statement",
    )
    framework_mappings: list[str] = Field(
        default_factory=list,
        description="Framework control IDs this risk maps to",
    )
    model_inventory_ref: str | None = Field(
        default=None,
        description=(
            "v0.7.10+ SR 11-7 / SR 26-02 / OCC Bulletin 2011-12 / OCC "
            "Bulletin 2026-13a model risk management linkage — UUID of "
            "the `evidentia_core.models.model_risk.ModelInventory` "
            "record describing the model that produced this risk "
            "statement. Optional in v0.7.x to preserve deserialization "
            "compat with pre-v0.7.10 RiskStatement payloads. Required "
            "for any risk statement consumed by federally-regulated "
            "model-risk-management programs (banks, insurers, "
            "broker-dealers). Operators wire the linkage via "
            "`RiskStatementGenerator(model_inventory_id=...)`."
        ),
    )
    reasoning_trace: ReasoningTrace | None = Field(
        default=None,
        description=(
            "v0.8.0 P0.2 Policy Reasoning Trace per arXiv 2509.23291. "
            "Optional structured decomposition of the risk statement "
            "into atomic claims + per-claim clause citations + "
            "confidence scores. Populated when the operator passes "
            "``--emit-trace`` to ``evidentia risk generate`` (or "
            "``emit_trace=True`` on ``RiskStatementGenerator.generate``). "
            "Backward compatible — pre-v0.8.0 deserialization still "
            "succeeds with this field defaulting to None. When present, "
            "OSCAL emit surfaces the trace in back-matter as an "
            "Evidentia-namespaced resource so trestle-conformance "
            "round-trips preserve it."
        ),
    )
    tags: list[str] = Field(default_factory=list)


class RiskRegister(EvidentiaModel):
    """A collection of risk statements for an organization/system."""

    id: str = Field(default_factory=new_id)
    organization: str
    system_name: str
    generated_at: datetime = Field(default_factory=utc_now)
    risks: list[RiskStatement] = Field(default_factory=list)
    evidentia_version: str = Field(
        default_factory=current_version,
        description="Version of evidentia-core that produced this register",
    )

    @property
    def critical_count(self) -> int:
        return sum(1 for r in self.risks if r.risk_level == RiskLevel.CRITICAL.value)

    @property
    def high_count(self) -> int:
        return sum(1 for r in self.risks if r.risk_level == RiskLevel.HIGH.value)

    @property
    def accepted_count(self) -> int:
        return sum(1 for r in self.risks if r.accepted)

    @property
    def pending_review_count(self) -> int:
        return sum(1 for r in self.risks if not r.reviewed_by)
