"""Risk statement models following NIST SP 800-30 structure.

Risk statements are generated by the AI module based on identified gaps
and system context. Each statement includes structured threat analysis,
likelihood/impact ratings, and remediation recommendations.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import Field

from evidentia_core.audit.provenance import GenerationContext
from evidentia_core.models.common import (
    EvidentiaModel,
    current_version,
    new_id,
    utc_now,
)


class RiskLevel(str, Enum):
    """Overall risk level (derived from likelihood × impact)."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFORMATIONAL = "informational"


class LikelihoodRating(str, Enum):
    """Likelihood that a threat event will occur (NIST SP 800-30 scale)."""

    VERY_HIGH = "very_high"
    HIGH = "high"
    MODERATE = "moderate"
    LOW = "low"
    VERY_LOW = "very_low"


class ImpactRating(str, Enum):
    """Impact if the threat event occurs (NIST SP 800-30 scale)."""

    VERY_HIGH = "very_high"
    HIGH = "high"
    MODERATE = "moderate"
    LOW = "low"
    VERY_LOW = "very_low"


class RiskTreatment(str, Enum):
    """Risk treatment decision."""

    MITIGATE = "mitigate"
    ACCEPT = "accept"
    TRANSFER = "transfer"
    AVOID = "avoid"
    PENDING = "pending"


class RiskStatement(EvidentiaModel):
    """A structured risk statement following NIST SP 800-30 Rev 1 format.

    The structure follows the NIST risk equation:
    Risk = Likelihood(Threat × Vulnerability) × Impact
    """

    id: str = Field(default_factory=new_id)
    # ── Core NIST SP 800-30 risk statement components ──────────────────
    asset: str = Field(
        description="The system, data, function, or process at risk",
    )
    threat_source: str = Field(
        description="Who or what could exploit the vulnerability",
    )
    threat_event: str = Field(
        description="What the threat source would do",
    )
    vulnerability: str = Field(
        description="The specific weakness that enables the threat",
    )
    predisposing_conditions: list[str] = Field(
        default_factory=list,
        description="Environmental factors that increase likelihood",
    )
    # ── Ratings ────────────────────────────────────────────────────────
    likelihood: LikelihoodRating = Field(
        description="Likelihood that the threat event will occur",
    )
    likelihood_rationale: str = Field(
        description="Specific explanation for the likelihood rating",
    )
    impact: ImpactRating = Field(
        description="Impact if the threat event occurs",
    )
    impact_rationale: str = Field(
        description="Specific explanation for the impact rating",
    )
    risk_level: RiskLevel = Field(
        description="Overall risk level derived from likelihood × impact",
    )
    risk_description: str = Field(
        description="Full prose risk statement combining all components",
    )
    # ── Remediation ────────────────────────────────────────────────────
    recommended_controls: list[str] = Field(
        description="NIST 800-53 control IDs that would mitigate this risk",
    )
    remediation_priority: int = Field(
        ge=1,
        le=5,
        description="1 = most urgent, 5 = least urgent",
    )
    remediation_steps: list[str] = Field(
        default_factory=list,
        description="Ordered list of specific remediation actions",
    )
    estimated_remediation_effort: str | None = Field(
        default=None,
        description="Estimated effort: 'hours', 'days', 'weeks', 'months'",
    )
    # ── Treatment ──────────────────────────────────────────────────────
    treatment: RiskTreatment = Field(
        default=RiskTreatment.PENDING,
        description="Risk treatment decision",
    )
    treatment_rationale: str | None = Field(
        default=None,
        description="Rationale for the treatment decision (required if accepted)",
    )
    # ── Lifecycle ──────────────────────────────────────────────────────
    generated_by: str = Field(
        default="evidentia-ai",
        description="'evidentia-ai' for generated, or user email for manual",
    )
    generated_at: datetime = Field(default_factory=utc_now)
    model_used: str | None = Field(
        default=None,
        description="LLM model used for generation",
    )
    generation_context: GenerationContext | None = Field(
        default=None,
        description=(
            "v0.7.1+ AI provenance block — model, temperature, prompt_hash, "
            "run_id, attempts. Optional in v0.7.x to preserve deserialization "
            "compat with pre-v0.7.1 RiskStatement payloads; will be tightened "
            "to required in v0.8 with a deprecation cycle. "
            "See ``evidentia_core.audit.provenance.GenerationContext``."
        ),
    )
    reviewed_by: str | None = Field(default=None)
    reviewed_at: datetime | None = Field(default=None)
    accepted: bool = Field(
        default=False,
        description="Whether this risk statement has been accepted by a reviewer",
    )
    # ── Mappings ───────────────────────────────────────────────────────
    source_gap_id: str | None = Field(
        default=None,
        description="ID of the ControlGap that triggered this risk statement",
    )
    framework_mappings: list[str] = Field(
        default_factory=list,
        description="Framework control IDs this risk maps to",
    )
    tags: list[str] = Field(default_factory=list)


class RiskRegister(EvidentiaModel):
    """A collection of risk statements for an organization/system."""

    id: str = Field(default_factory=new_id)
    organization: str
    system_name: str
    generated_at: datetime = Field(default_factory=utc_now)
    risks: list[RiskStatement] = Field(default_factory=list)
    evidentia_version: str = Field(
        default_factory=current_version,
        description="Version of evidentia-core that produced this register",
    )

    @property
    def critical_count(self) -> int:
        return sum(1 for r in self.risks if r.risk_level == RiskLevel.CRITICAL.value)

    @property
    def high_count(self) -> int:
        return sum(1 for r in self.risks if r.risk_level == RiskLevel.HIGH.value)

    @property
    def accepted_count(self) -> int:
        return sum(1 for r in self.risks if r.accepted)

    @property
    def pending_review_count(self) -> int:
        return sum(1 for r in self.risks if not r.reviewed_by)
