#!/usr/bin/env python3
"""Deterministic generator for the 7 per-package API reference pages (D6 Batch 2).

Generates ``docs/wiki/4-reference/api/<pkg>.md`` — one concise public-surface
index per Python workspace package — for the GitHub wiki.

Why a public-surface index, not mkdocstrings
---------------------------------------------
The plan originally proposed mkdocstrings HTML extraction. That does NOT
translate to a committed plain-markdown GitHub wiki: mkdocstrings renders
rich HTML *inside an MkDocs build* and produces nothing a flat ``.md`` wiki
page can carry. So this generator takes **Option B** — a maintainable,
plain-markdown public-surface index per package:

* the package's one-line purpose (its ``pyproject.toml`` ``[project]
  .description``),
* its public symbols — ``__all__`` when the ``__init__.py`` declares one,
  else the public (non-underscore) names *defined or imported* at the top of
  ``__init__.py`` — each with the first line of its docstring where it can be
  read statically,
* its public submodules / subpackages (a navigation aid — several packages
  intentionally keep a thin ``__init__.py`` and surface their API via
  submodules), and
* a pointer to the source tree + the live MkDocs API site for the full,
  always-current type signatures.

All extraction is AST / static-text based — no package is imported, so the
generator runs deterministically and does not need the project installed
(unlike ``sync_reference.py``'s CLI page). Ordering is sorted throughout.

The 7 packages documented: evidentia-core, evidentia-ai, evidentia-mcp,
evidentia-collectors, evidentia-api, evidentia-eval, evidentia-integrations.
The top-level ``evidentia`` CLI meta-package is covered by ``cli.md``;
``evidentia-ui`` is a TS/JS frontend, not a Python API.

Modes
-----
``sync_api_docs.py``
    Generate / update all 7 API pages in place under
    ``docs/wiki/4-reference/api/``.
``sync_api_docs.py --check``
    Do not write. Exit 0 if every committed page matches what would be
    regenerated; exit 1 + print which pages drifted. (CI / pre-tag gate;
    wired into ``sync-wiki.yml`` before the wiki push.)

Per the publishing-authority protocol (~/.claude/CLAUDE.md), this script
NEVER pushes, tags, or publishes. It only reads source/data + writes the
in-tree wiki API pages.
"""

from __future__ import annotations

import argparse
import ast
import sys
import tomllib
from pathlib import Path

# scripts/wiki/sync_api_docs.py -> repo root is two parents up.
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

BLOB_URL_BASE = "https://github.com/Polycentric-Labs/evidentia/blob/main"
GENERATOR_REL = "scripts/wiki/sync_api_docs.py"

# Base URL of the live MkDocs API site (mkdocstrings-rendered full
# signatures). The per-symbol HTML anchors live under this site; the page
# points readers here for the always-current detail the flat wiki can't carry.
MKDOCS_API_BASE = "https://polycentric-labs.github.io/evidentia/reference/api"

# The 7 Python packages to document, as (distribution-name, import-module).
# Order = the rendered/section order (matches the 4-reference/index.md list).
PACKAGES: tuple[tuple[str, str], ...] = (
    ("evidentia-core", "evidentia_core"),
    ("evidentia-ai", "evidentia_ai"),
    ("evidentia-mcp", "evidentia_mcp"),
    ("evidentia-collectors", "evidentia_collectors"),
    ("evidentia-api", "evidentia_api"),
    ("evidentia-eval", "evidentia_eval"),
    ("evidentia-integrations", "evidentia_integrations"),
)

# Symbols never worth listing as public API even if they appear at module
# scope / in __all__. These are import boilerplate that leaks into a thin
# package root: the version dunder, ``from __future__ import annotations``,
# and the importlib-metadata helpers every package's ``__version__`` shim
# imports (``PackageNotFoundError`` + the ``version as _pkg_version`` alias,
# already underscore-filtered). Filtering them lets a thin root render
# honestly as "exposes only __version__".
_SYMBOL_DENYLIST: frozenset[str] = frozenset(
    {"__version__", "annotations", "PackageNotFoundError"}
)


# ---------------------------------------------------------------------------
# Shared helpers (pure).
# ---------------------------------------------------------------------------


def build_banner(dist_name: str) -> str:
    """Build the auto-generated header banner for a package API page."""
    return (
        f"<!-- AUTO-GENERATED by {GENERATOR_REL} -- do not edit directly -->\n"
        f"# `{dist_name}` API\n\n"
        f"> **Auto-generated page.** This public-surface index is generated "
        f"from the package source by [`{GENERATOR_REL}`]({BLOB_URL_BASE}/"
        f"{GENERATOR_REL}). Do not edit it by hand; change the package and "
        f"re-run the generator (`uv run python {GENERATOR_REL}`).\n\n"
    )


def first_docstring_line(docstring: str | None) -> str:
    """Return the first non-empty line of a docstring (stripped), or ""."""
    if not docstring:
        return ""
    for line in docstring.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


# ---------------------------------------------------------------------------
# Extraction (pure: operates on source text / directory listings).
# ---------------------------------------------------------------------------


def read_description(pyproject_text: str) -> str:
    """Return ``[project].description`` from a pyproject.toml's text (pure)."""
    data = tomllib.loads(pyproject_text)
    project = data.get("project", {})
    description = project.get("description", "")
    return str(description).strip()


def _string_constants(seq: ast.List | ast.Tuple) -> list[str]:
    """Return the string-constant elements of an AST list/tuple node.

    Non-string elements are skipped. Reads the literal values directly off
    the AST ``Constant`` nodes (no expression evaluation of any kind).
    """
    out: list[str] = []
    for element in seq.elts:
        if isinstance(element, ast.Constant) and isinstance(element.value, str):
            out.append(element.value)
    return out


def extract_all_list(init_source: str) -> list[str] | None:
    """Return the literal ``__all__`` list from ``__init__.py`` source, or None.

    Reads a module-level ``__all__ = [...]`` / ``(...)`` assignment by pulling
    the string-constant elements straight off the AST list/tuple node (no
    expression evaluation). Returns ``None`` when no ``__all__`` is declared,
    so the caller can fall back to the top-level public-name scan.
    """
    tree = ast.parse(init_source)
    for node in tree.body:
        targets: list[ast.expr] = []
        value: ast.expr | None = None
        if isinstance(node, ast.Assign):
            targets = node.targets
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
            value = node.value
        else:
            continue
        is_all = any(
            isinstance(t, ast.Name) and t.id == "__all__" for t in targets
        )
        if not is_all:
            continue
        if isinstance(value, (ast.List, ast.Tuple)):
            return _string_constants(value)
        return None
    return None


def extract_public_toplevel_names(init_source: str) -> list[str]:
    """Return public names defined OR imported at ``__init__.py`` top level.

    Used when no ``__all__`` is declared. Collects: top-level ``def`` / ``class``
    names, top-level assignment target names, and names bound by ``import`` /
    ``from ... import`` statements — excluding any leading-underscore name and
    the denylist. Deterministic (de-duplicated + sorted by the caller).
    """
    tree = ast.parse(init_source)
    names: set[str] = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            for alias in node.names:
                # The bound name is the asname when present, else the leaf of
                # the imported dotted name.
                bound = alias.asname or alias.name.split(".")[0]
                names.add(bound)
    return sorted(
        n for n in names if not n.startswith("_") and n not in _SYMBOL_DENYLIST
    )


def build_symbol_docs(package_dir: Path, symbols: list[str]) -> list[tuple[str, str]]:
    """Pair each public symbol with its first docstring line where readable.

    For a symbol whose definition lives in ``<package_dir>/<module>.py`` and
    is re-exported from ``__init__.py`` (the common pattern), the docstring is
    read statically by scanning the package's top-level modules for a matching
    ``def``/``class``. Symbols whose docstring can't be located statically get
    an empty summary (the live MkDocs site carries the detail). Pure aside
    from reading the package's own source files.

    Returns ``[(symbol, summary), ...]`` in the input ``symbols`` order.
    """
    # Build a {name: first-docstring-line} index from every top-level module's
    # public defs/classes. One pass over the package's immediate .py files +
    # the __init__.py of immediate subpackages.
    doc_index: dict[str, str] = {}
    source_files: list[Path] = sorted(package_dir.glob("*.py"))
    for sub in sorted(p for p in package_dir.iterdir() if p.is_dir()):
        init = sub / "__init__.py"
        if init.exists():
            source_files.append(init)
    for src in source_files:
        try:
            tree = ast.parse(src.read_text(encoding="utf-8"))
        except (OSError, SyntaxError):  # pragma: no cover — defensive
            continue
        for node in tree.body:
            if isinstance(
                node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
            ) and node.name not in doc_index:
                doc_index[node.name] = first_docstring_line(
                    ast.get_docstring(node)
                )
    return [(symbol, doc_index.get(symbol, "")) for symbol in symbols]


def list_public_submodules(package_dir: Path) -> list[str]:
    """Return the package's public submodules + subpackages (sorted).

    A submodule is a non-underscore ``*.py`` file directly under
    ``package_dir`` (excluding ``__init__.py``); a subpackage is a
    non-underscore directory that contains an ``__init__.py`` (so the React
    ``static/`` build dir and ``__pycache__`` are excluded). Names only — the
    navigation aid, deterministic.
    """
    names: set[str] = set()
    for py_file in package_dir.glob("*.py"):
        stem = py_file.stem
        if not stem.startswith("_"):
            names.add(stem)
    for child in package_dir.iterdir():
        if (
            child.is_dir()
            and not child.name.startswith("_")
            and (child / "__init__.py").exists()
        ):
            names.add(child.name)
    return sorted(names)


# ---------------------------------------------------------------------------
# Render (pure).
# ---------------------------------------------------------------------------


def render_package_page(
    dist_name: str,
    module_name: str,
    description: str,
    symbol_docs: list[tuple[str, str]],
    has_explicit_all: bool,
    submodules: list[str],
) -> str:
    """Render one package's API page (pure)."""
    out = [build_banner(dist_name)]
    if description:
        out.append(f"{description}\n\n")
    out.append(
        f"Install: `pip install {dist_name}`. Import root: `{module_name}`.\n\n"
    )

    # --- Public symbols ---
    out.append("## Public API\n\n")
    if symbol_docs:
        if has_explicit_all:
            out.append(
                f"The names exported by `{module_name}.__all__` "
                f"(re-exported at the package root):\n\n"
            )
        else:
            out.append(
                f"The public names available at the `{module_name}` package "
                f"root:\n\n"
            )
        out.append("| Symbol | Summary |\n| --- | --- |\n")
        for symbol, summary in symbol_docs:
            cell_summary = summary.replace("|", r"\|").strip() or "—"
            out.append(f"| `{symbol}` | {cell_summary} |\n")
        out.append("\n")
    else:
        out.append(
            f"`{module_name}` keeps a thin package root (it exposes only "
            f"`__version__`); its API surface lives in the submodules listed "
            f"below.\n\n"
        )

    # --- Submodules ---
    if submodules:
        out.append("## Submodules\n\n")
        out.append(
            f"Public submodules + subpackages of `{module_name}` (import "
            f"directly, e.g. `from {module_name}.{submodules[0]} import ...`):"
            f"\n\n"
        )
        for sub in submodules:
            out.append(f"- `{module_name}.{sub}`\n")
        out.append("\n")

    # --- Pointers ---
    out.append("## Full signatures\n\n")
    out.append(
        f"This page is a public-surface index. For full, always-current type "
        f"signatures and rendered docstrings, see the "
        f"[live API reference]({MKDOCS_API_BASE}/{module_name}/) (built from "
        f"the source with mkdocstrings) or read the "
        f"[source]({BLOB_URL_BASE}/packages/{dist_name}/src/{module_name}).\n"
    )
    return "".join(out)


# ---------------------------------------------------------------------------
# Orchestration.
# ---------------------------------------------------------------------------


def package_init_path(repo_root: Path, dist_name: str, module_name: str) -> Path:
    """Return the path to a package's ``__init__.py``."""
    return (
        repo_root
        / "packages"
        / dist_name
        / "src"
        / module_name
        / "__init__.py"
    )


def generate_page(repo_root: Path, dist_name: str, module_name: str) -> str:
    """Render the API page for a single package (reads that package's source)."""
    pkg_root = repo_root / "packages" / dist_name
    init_path = package_init_path(repo_root, dist_name, module_name)
    package_dir = init_path.parent

    description = read_description(
        (pkg_root / "pyproject.toml").read_text(encoding="utf-8")
    )
    init_source = init_path.read_text(encoding="utf-8")

    explicit_all = extract_all_list(init_source)
    if explicit_all is not None:
        symbols = sorted(s for s in explicit_all if s not in _SYMBOL_DENYLIST)
        has_explicit_all = True
    else:
        symbols = extract_public_toplevel_names(init_source)
        has_explicit_all = False

    symbol_docs = build_symbol_docs(package_dir, symbols)
    submodules = list_public_submodules(package_dir)
    return render_package_page(
        dist_name,
        module_name,
        description,
        symbol_docs,
        has_explicit_all,
        submodules,
    )


def page_rel_path(dist_name: str) -> str:
    """Return the repo-relative output path for a package's API page."""
    return f"docs/wiki/4-reference/api/{dist_name}.md"


def generate_all(repo_root: Path = REPO_ROOT) -> dict[str, str]:
    """Render every package API page; return ``{page_rel_path: rendered_text}``."""
    out: dict[str, str] = {}
    for dist_name, module_name in PACKAGES:
        out[page_rel_path(dist_name)] = generate_page(
            repo_root, dist_name, module_name
        )
    return out


# ---------------------------------------------------------------------------
# Compare (--check) + CLI.
# ---------------------------------------------------------------------------


def _diff_summary(expected: str, actual: str, name: str) -> str:
    """Return a short first-divergence summary between two text blobs."""
    exp_lines = expected.splitlines()
    act_lines = actual.splitlines()
    for i, (exp, act) in enumerate(zip(exp_lines, act_lines, strict=False)):
        if exp != act:
            return (
                f"  {name}: first diff at line {i + 1}\n"
                f"    committed:   {exp!r}\n"
                f"    regenerated: {act!r}"
            )
    if len(exp_lines) != len(act_lines):
        return (
            f"  {name}: line-count differs "
            f"(committed={len(exp_lines)}, regenerated={len(act_lines)})"
        )
    return f"  {name}: content differs only in trailing bytes / EOL"


def compare(rendered: dict[str, str], repo_root: Path = REPO_ROOT) -> list[str]:
    """Compare rendered pages against the committed files on disk (read-only)."""
    drift: list[str] = []
    for page_rel, content in sorted(rendered.items()):
        committed_path = repo_root / page_rel
        if not committed_path.exists():
            drift.append(f"  {page_rel}: committed page missing")
            continue
        committed = committed_path.read_text(encoding="utf-8")
        if committed != content:
            drift.append(_diff_summary(committed, content, page_rel))
    return drift


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Do not write. Exit 0 if every committed API page matches what "
            "would be regenerated from the package source; exit 1 + print a "
            "drift summary on divergence. (CI / pre-tag gate.)"
        ),
    )
    args = parser.parse_args(argv)

    rendered = generate_all()

    if args.check:
        drift = compare(rendered)
        if drift:
            print(
                "DRIFT: committed wiki API pages differ from the package "
                "source:",
                file=sys.stderr,
            )
            for line in drift:
                print(line, file=sys.stderr)
            print(
                f"\nRe-run `uv run python {GENERATOR_REL}` (no --check) to "
                "regenerate the pages, then commit.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: all {len(rendered)} wiki API pages match the package source.")
        return 0

    for page_rel, content in rendered.items():
        out_path = REPO_ROOT / page_rel
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"  wrote {page_rel}")
    print(f"Generated {len(rendered)} wiki API pages from package source.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
