"""Curated event vocabulary for Evidentia structured logs (v0.7.0).

Rather than letting every caller invent its own ``event.action`` string,
we enumerate the full set here. Operators building SIEM alerts, FedRAMP
3PAOs running audit queries, and Big-4 reviewers correlating evidence
all need a stable vocabulary they can pin to. Ad-hoc action names break
audit-trail continuity across releases; a registry fixes the vocabulary
so a query like ``event.action:evidentia.collect.finding_retrieved`` is
meaningful at v0.6.0, v0.7.0, and v0.8.0 alike.

Adding a new event:
    1. Append to :class:`EventAction`.
    2. Document in ``docs/log-schema.md``.
    3. Add a test in ``tests/unit/test_audit/test_events.py`` asserting the
       name matches the ``evidentia.<namespace>.<verb>`` convention.

ECS categorization primers (see https://www.elastic.co/guide/en/ecs/):

- ``event.category`` = coarse bucket (``configuration``, ``iam``, ``process``)
- ``event.type`` = action-specific sub-type (``info``, ``change``, ``error``)
- ``event.outcome`` = outcome (``success``, ``failure``, ``unknown``)

NIST SP 800-53 Rev 5 AU-3 (Content of Audit Records) requires each
audit record to capture: what happened, when, where, source, outcome,
and identity. The structured logger populates all six from the fields
documented below plus the :class:`EventAction` vocabulary.
"""

from __future__ import annotations

from enum import Enum


class EventAction(str, Enum):
    """Authoritative list of ``event.action`` values emitted by Evidentia.

    Names follow the ``evidentia.<namespace>.<verb>`` convention so SIEM
    operators can filter by prefix (e.g., ``event.action:evidentia.collect.*``).
    Unknown actions are accepted by the logger but tagged with a warning
    so audit-reviewers see the full picture while we learn what emitters
    are missing from this registry.
    """

    # Collection lifecycle ─ the verbs that move a collector from "starting"
    # to "completed". A run begins with COLLECT_STARTED, ends with either
    # COLLECT_COMPLETED (clean) or COLLECT_FAILED / COLLECT_ABORTED.
    COLLECT_STARTED = "evidentia.collect.started"
    COLLECT_FINDING_RETRIEVED = "evidentia.collect.finding_retrieved"
    COLLECT_FINDING_SKIPPED = "evidentia.collect.finding_skipped"
    COLLECT_PAGE_FETCHED = "evidentia.collect.page_fetched"
    COLLECT_RETRY = "evidentia.collect.retry"
    COLLECT_COMPLETED = "evidentia.collect.completed"
    COLLECT_FAILED = "evidentia.collect.failed"
    COLLECT_ABORTED = "evidentia.collect.aborted"

    # Authentication events ─ tracks credential resolution at collection time.
    # Required by NIST SP 800-53 AU-2 (Event Logging) to identify the
    # authenticating principal on every evidence record.
    AUTH_CREDENTIAL_RESOLVED = "evidentia.auth.credential_resolved"
    AUTH_CREDENTIAL_REFRESH = "evidentia.auth.credential_refresh"
    AUTH_CREDENTIAL_FAILED = "evidentia.auth.credential_failed"

    # Configuration events ─ config loaded, overridden, or rejected.
    # Required for H12 (config audit trail) of the enterprise checklist.
    CONFIG_LOADED = "evidentia.config.loaded"
    CONFIG_RESOLVED = "evidentia.config.resolved"
    CONFIG_OVERRIDE_APPLIED = "evidentia.config.override_applied"
    CONFIG_INVALID = "evidentia.config.invalid"

    # Signing events ─ GPG and Sigstore cover distinct signing paths.
    # SIGSTORE_SKIPPED_AIRGAP emitted when Sigstore is requested but
    # air-gap mode forbids the Fulcio/Rekor network calls.
    SIGN_GPG_SIGNED = "evidentia.sign.gpg_signed"
    SIGN_SIGSTORE_SIGNED = "evidentia.sign.sigstore_signed"
    SIGN_SIGSTORE_SKIPPED_AIRGAP = "evidentia.sign.sigstore_skipped_airgap"
    SIGN_FAILED = "evidentia.sign.signing_failed"

    # Verification events ─ mirror SIGN_* for the verify path. Digest and
    # signature outcomes are emitted separately so auditors can filter on
    # either dimension.
    VERIFY_STARTED = "evidentia.verify.started"
    VERIFY_DIGEST_PASSED = "evidentia.verify.digest_passed"
    VERIFY_DIGEST_FAILED = "evidentia.verify.digest_failed"
    VERIFY_SIGNATURE_PASSED = "evidentia.verify.signature_passed"
    VERIFY_SIGNATURE_FAILED = "evidentia.verify.signature_failed"
    VERIFY_COMPLETED = "evidentia.verify.completed"

    # Manifest events ─ completeness attestation B5 emits these. Empty-set
    # attestation is a first-class event so "no findings" is distinguishable
    # from "collection failed" in the audit log.
    MANIFEST_GENERATED = "evidentia.manifest.generated"
    MANIFEST_EMPTY_SET_ATTESTED = "evidentia.manifest.empty_set_attested"
    MANIFEST_INCOMPLETE = "evidentia.manifest.incomplete"

    # AI generation events (v0.7.1) ─ emitted by evidentia-ai's risk-statement
    # and plain-English-explanation generators. Distinct namespace from
    # collect.* because these outputs are generated by an LLM rather than
    # collected from a source system; an auditor querying for "what produced
    # this artifact" needs to distinguish the two paths.
    #
    # Per-call events fire once per gap/control. The matching ``*_BATCH_COMPLETED``
    # event fires once at end-of-batch with succeeded/total counts, so SIEM
    # operators can distinguish "100 risks generated across 100 batches" from
    # "100 risks generated in 1 batch" without double-counting per-call events.
    AI_RISK_GENERATED = "evidentia.ai.risk_generated"
    AI_RISK_FAILED = "evidentia.ai.risk_failed"
    AI_RISK_RETRY = "evidentia.ai.risk_retry"
    AI_RISK_BATCH_COMPLETED = "evidentia.ai.risk_batch_completed"
    AI_EXPLAIN_GENERATED = "evidentia.ai.explain_generated"
    AI_EXPLAIN_FAILED = "evidentia.ai.explain_failed"
    AI_EXPLAIN_RETRY = "evidentia.ai.explain_retry"
    AI_EXPLAIN_CACHE_HIT = "evidentia.ai.explain_cache_hit"
    AI_EXPLAIN_BATCH_COMPLETED = "evidentia.ai.explain_batch_completed"

    # v0.8.0 P0.1: AI determinism + faithfulness evaluation harness
    # (DFAH per arXiv 2601.15322). Each ``evidentia eval`` invocation
    # emits a STARTED + COMPLETED pair, plus one
    # DETERMINISM_VIOLATION / FAITHFULNESS_VIOLATION event per
    # failed sample so an auditor can reconstruct exactly which
    # sample(s) triggered a CI gate failure.
    AI_EVAL_STARTED = "evidentia.ai.eval_started"
    AI_EVAL_DETERMINISM_VIOLATION = "evidentia.ai.eval_determinism_violation"
    AI_EVAL_FAITHFULNESS_VIOLATION = "evidentia.ai.eval_faithfulness_violation"
    AI_EVAL_COMPLETED = "evidentia.ai.eval_completed"
    # v0.8.2 P3.2: first-class Sigstore signing for `evidentia eval`
    # output. Fired once per eval invocation that opts in to --sign;
    # the bundle path lands in evidentia.bundle_path so an auditor
    # can correlate the EvalResult JSON with its Sigstore proof.
    AI_EVAL_OUTPUT_SIGNED = "evidentia.ai.eval_output_signed"

    # v0.8.0 P0.2: Policy Reasoning Trace emit (arXiv 2509.23291).
    # Fired once per RiskStatement (or future trace-bearing
    # artifact) when the operator opts in to ``--emit-trace``.
    # Lets auditors reconstruct exactly which artifacts carry a
    # trace and which do not, plus the trace's overall_confidence
    # for fast filtering of low-confidence outputs.
    AI_RISK_TRACE_EMITTED = "evidentia.ai.risk_trace_emitted"

    # Retention + WORM lifecycle events (v0.7.12 P1) — audit-trail
    # actions on records under retention metadata. The PURGED variant
    # serves as the canonical legal-counsel-defensible artifact for
    # GDPR Article 17 (right-to-erasure) executions: every purge
    # call emits one event with the operator identity + GDPR
    # request reference, persisted to the audit log INDEPENDENT of
    # the record itself (which has been deleted).
    RETENTION_RECORD_PUT = "evidentia.retention.record_put"
    RETENTION_RECORD_EXTENDED = "evidentia.retention.record_extended"
    RETENTION_LEGAL_HOLD_APPLIED = "evidentia.retention.legal_hold_applied"
    RETENTION_LEGAL_HOLD_RELEASED = "evidentia.retention.legal_hold_released"
    RETENTION_LIFECYCLE_TRANSITIONED = "evidentia.retention.lifecycle_transitioned"
    RETENTION_RECORD_PURGED = "evidentia.retention.record_purged"
    RETENTION_GDPR_PURGE = "evidentia.retention.gdpr_purge"


class EventCategory(str, Enum):
    """ECS ``event.category`` values Evidentia uses.

    ECS defines a controlled vocabulary for event.category. We use a
    subset relevant to GRC evidence collection.
    """

    CONFIGURATION = "configuration"
    IAM = "iam"
    AUTHENTICATION = "authentication"
    PROCESS = "process"
    FILE = "file"
    NETWORK = "network"


class EventType(str, Enum):
    """ECS ``event.type`` values Evidentia uses."""

    INFO = "info"
    ACCESS = "access"
    ALLOWED = "allowed"
    CHANGE = "change"
    CREATION = "creation"
    DELETION = "deletion"
    END = "end"
    START = "start"
    ERROR = "error"


class EventOutcome(str, Enum):
    """ECS ``event.outcome`` values — pinned to the three-value ECS enum."""

    SUCCESS = "success"
    FAILURE = "failure"
    UNKNOWN = "unknown"
