#!/usr/bin/env python3
"""Dump the evidentia-api FastAPI OpenAPI schema to a JSON file.

This is the source-of-truth step in the GUI type-parity chain:

    FastAPI app  --(this script)-->  openapi.json  --(openapi-typescript)-->  src/types/openapi.ts

The committed ``packages/evidentia-ui/openapi.json`` is regenerated by this
script and checked for drift in CI (the Python ``test`` job runs it and
``git diff --exit-code``). The frontend job then regenerates the TypeScript
types from the committed JSON and checks *those* for drift. Together the two
gates make it impossible for the GUI's API types to silently lag the API.

Output is written with ``sort_keys=True`` + a trailing newline so the file
is deterministic and diff-stable across machines and Python runs.

Usage::

    python scripts/dump_openapi.py [OUTPUT_PATH]

``OUTPUT_PATH`` defaults to ``packages/evidentia-ui/openapi.json`` relative
to the repo root.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_OUT = _REPO_ROOT / "packages" / "evidentia-ui" / "openapi.json"


def dump(output_path: Path) -> None:
    """Write the FastAPI OpenAPI schema to ``output_path`` deterministically."""
    # Imported lazily so the script's --help works without the API installed.
    from evidentia_api.app import create_app

    schema = create_app().openapi()
    text = json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    out = Path(argv[1]) if len(argv) > 1 else _DEFAULT_OUT
    dump(out)
    print(f"Wrote OpenAPI schema -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
